DROP POLICY IF EXISTS "Authenticated users can delete IP documents" ON storage.objects;
CREATE POLICY "Authenticated users can delete IP documents" ON storage.objects AS PERMISSIVE FOR DELETE TO authenticated USING ((bucket_id = 'ip-documents'::text));
DROP POLICY IF EXISTS "Authenticated users can delete audit assets" ON storage.objects;
CREATE POLICY "Authenticated users can delete audit assets" ON storage.objects AS PERMISSIVE FOR DELETE TO authenticated USING ((bucket_id = 'audit-assets'::text));
DROP POLICY IF EXISTS "Authenticated users can delete audit attachments" ON storage.objects;
CREATE POLICY "Authenticated users can delete audit attachments" ON storage.objects AS PERMISSIVE FOR DELETE TO authenticated USING ((bucket_id = 'audit-attachments'::text));
DROP POLICY IF EXISTS "Authenticated users can delete bn evidence" ON storage.objects;
CREATE POLICY "Authenticated users can delete bn evidence" ON storage.objects AS PERMISSIVE FOR DELETE TO authenticated USING ((bucket_id = 'bn-evidence'::text));
DROP POLICY IF EXISTS "Authenticated users can delete employer documents" ON storage.objects;
CREATE POLICY "Authenticated users can delete employer documents" ON storage.objects AS PERMISSIVE FOR DELETE TO authenticated USING ((bucket_id = 'employer-documents'::text));
DROP POLICY IF EXISTS "Authenticated users can delete ia-artifacts" ON storage.objects;
CREATE POLICY "Authenticated users can delete ia-artifacts" ON storage.objects AS PERMISSIVE FOR DELETE TO authenticated USING ((bucket_id = 'ia-artifacts'::text));
DROP POLICY IF EXISTS "Authenticated users can read audit attachments" ON storage.objects;
CREATE POLICY "Authenticated users can read audit attachments" ON storage.objects AS PERMISSIVE FOR SELECT TO authenticated USING ((bucket_id = 'audit-attachments'::text));
DROP POLICY IF EXISTS "Authenticated users can read bn evidence" ON storage.objects;
CREATE POLICY "Authenticated users can read bn evidence" ON storage.objects AS PERMISSIVE FOR SELECT TO authenticated USING ((bucket_id = 'bn-evidence'::text));
DROP POLICY IF EXISTS "Authenticated users can read employer documents" ON storage.objects;
CREATE POLICY "Authenticated users can read employer documents" ON storage.objects AS PERMISSIVE FOR SELECT TO authenticated USING ((bucket_id = 'employer-documents'::text));
DROP POLICY IF EXISTS "Authenticated users can read ia-artifacts" ON storage.objects;
CREATE POLICY "Authenticated users can read ia-artifacts" ON storage.objects AS PERMISSIVE FOR SELECT TO authenticated USING ((bucket_id = 'ia-artifacts'::text));
DROP POLICY IF EXISTS "Authenticated users can update audit assets" ON storage.objects;
CREATE POLICY "Authenticated users can update audit assets" ON storage.objects AS PERMISSIVE FOR UPDATE TO authenticated USING ((bucket_id = 'audit-assets'::text));
DROP POLICY IF EXISTS "Authenticated users can update audit attachments" ON storage.objects;
CREATE POLICY "Authenticated users can update audit attachments" ON storage.objects AS PERMISSIVE FOR UPDATE TO authenticated USING ((bucket_id = 'audit-attachments'::text));
DROP POLICY IF EXISTS "Authenticated users can update bn evidence" ON storage.objects;
CREATE POLICY "Authenticated users can update bn evidence" ON storage.objects AS PERMISSIVE FOR UPDATE TO authenticated USING ((bucket_id = 'bn-evidence'::text));
DROP POLICY IF EXISTS "Authenticated users can update employer documents" ON storage.objects;
CREATE POLICY "Authenticated users can update employer documents" ON storage.objects AS PERMISSIVE FOR UPDATE TO authenticated USING ((bucket_id = 'employer-documents'::text));
DROP POLICY IF EXISTS "Authenticated users can update ia-artifacts" ON storage.objects;
CREATE POLICY "Authenticated users can update ia-artifacts" ON storage.objects AS PERMISSIVE FOR UPDATE TO authenticated USING ((bucket_id = 'ia-artifacts'::text));
DROP POLICY IF EXISTS "Authenticated users can upload IP documents" ON storage.objects;
CREATE POLICY "Authenticated users can upload IP documents" ON storage.objects AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((bucket_id = 'ip-documents'::text));
DROP POLICY IF EXISTS "Authenticated users can upload audit assets" ON storage.objects;
CREATE POLICY "Authenticated users can upload audit assets" ON storage.objects AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((bucket_id = 'audit-assets'::text));
DROP POLICY IF EXISTS "Authenticated users can upload audit attachments" ON storage.objects;
CREATE POLICY "Authenticated users can upload audit attachments" ON storage.objects AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((bucket_id = 'audit-attachments'::text));
DROP POLICY IF EXISTS "Authenticated users can upload bn evidence" ON storage.objects;
CREATE POLICY "Authenticated users can upload bn evidence" ON storage.objects AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((bucket_id = 'bn-evidence'::text));
DROP POLICY IF EXISTS "Authenticated users can upload employer documents" ON storage.objects;
CREATE POLICY "Authenticated users can upload employer documents" ON storage.objects AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((bucket_id = 'employer-documents'::text));
DROP POLICY IF EXISTS "Authenticated users can upload ia-artifacts" ON storage.objects;
CREATE POLICY "Authenticated users can upload ia-artifacts" ON storage.objects AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((bucket_id = 'ia-artifacts'::text));
DROP POLICY IF EXISTS "Authenticated users can view IP documents" ON storage.objects;
CREATE POLICY "Authenticated users can view IP documents" ON storage.objects AS PERMISSIVE FOR SELECT TO authenticated USING ((bucket_id = 'ip-documents'::text));
DROP POLICY IF EXISTS "Delete legal contract docs" ON storage.objects;
CREATE POLICY "Delete legal contract docs" ON storage.objects AS PERMISSIVE FOR DELETE TO anon, authenticated USING ((bucket_id = 'legal-contract-docs'::text));
DROP POLICY IF EXISTS "Public read access for audit assets" ON storage.objects;
CREATE POLICY "Public read access for audit assets" ON storage.objects AS PERMISSIVE FOR SELECT TO public USING ((bucket_id = 'audit-assets'::text));
DROP POLICY IF EXISTS "Read legal contract docs" ON storage.objects;
CREATE POLICY "Read legal contract docs" ON storage.objects AS PERMISSIVE FOR SELECT TO anon, authenticated USING ((bucket_id = 'legal-contract-docs'::text));
DROP POLICY IF EXISTS "Update legal contract docs" ON storage.objects;
CREATE POLICY "Update legal contract docs" ON storage.objects AS PERMISSIVE FOR UPDATE TO anon, authenticated USING ((bucket_id = 'legal-contract-docs'::text));
DROP POLICY IF EXISTS "Upload legal contract docs" ON storage.objects;
CREATE POLICY "Upload legal contract docs" ON storage.objects AS PERMISSIVE FOR INSERT TO anon, authenticated WITH CHECK ((bucket_id = 'legal-contract-docs'::text));
DROP POLICY IF EXISTS audit_sig_auth_insert ON storage.objects;
CREATE POLICY audit_sig_auth_insert ON storage.objects AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((bucket_id = 'audit-signatures'::text));
DROP POLICY IF EXISTS audit_sig_auth_read ON storage.objects;
CREATE POLICY audit_sig_auth_read ON storage.objects AS PERMISSIVE FOR SELECT TO authenticated USING ((bucket_id = 'audit-signatures'::text));
DROP POLICY IF EXISTS audit_sig_auth_update ON storage.objects;
CREATE POLICY audit_sig_auth_update ON storage.objects AS PERMISSIVE FOR UPDATE TO authenticated USING ((bucket_id = 'audit-signatures'::text)) WITH CHECK ((bucket_id = 'audit-signatures'::text));
DROP POLICY IF EXISTS comm_assets_authenticated_delete ON storage.objects;
CREATE POLICY comm_assets_authenticated_delete ON storage.objects AS PERMISSIVE FOR DELETE TO authenticated USING ((bucket_id = 'comm-assets'::text));
DROP POLICY IF EXISTS comm_assets_authenticated_insert ON storage.objects;
CREATE POLICY comm_assets_authenticated_insert ON storage.objects AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((bucket_id = 'comm-assets'::text));
DROP POLICY IF EXISTS comm_assets_authenticated_select ON storage.objects;
CREATE POLICY comm_assets_authenticated_select ON storage.objects AS PERMISSIVE FOR SELECT TO authenticated USING ((bucket_id = 'comm-assets'::text));
DROP POLICY IF EXISTS comm_assets_authenticated_update ON storage.objects;
CREATE POLICY comm_assets_authenticated_update ON storage.objects AS PERMISSIVE FOR UPDATE TO authenticated USING ((bucket_id = 'comm-assets'::text)) WITH CHECK ((bucket_id = 'comm-assets'::text));
DROP POLICY IF EXISTS core_documents_delete_authenticated ON storage.objects;
CREATE POLICY core_documents_delete_authenticated ON storage.objects AS PERMISSIVE FOR DELETE TO authenticated USING ((bucket_id = 'core-documents'::text));
DROP POLICY IF EXISTS core_documents_read_authenticated ON storage.objects;
CREATE POLICY core_documents_read_authenticated ON storage.objects AS PERMISSIVE FOR SELECT TO authenticated USING ((bucket_id = 'core-documents'::text));
DROP POLICY IF EXISTS core_documents_update_authenticated ON storage.objects;
CREATE POLICY core_documents_update_authenticated ON storage.objects AS PERMISSIVE FOR UPDATE TO authenticated USING ((bucket_id = 'core-documents'::text));
DROP POLICY IF EXISTS core_documents_write_authenticated ON storage.objects;
CREATE POLICY core_documents_write_authenticated ON storage.objects AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((bucket_id = 'core-documents'::text));
DROP POLICY IF EXISTS "legal-referrals authenticated delete" ON storage.objects;
CREATE POLICY "legal-referrals authenticated delete" ON storage.objects AS PERMISSIVE FOR DELETE TO authenticated USING ((bucket_id = 'legal-referrals'::text));
DROP POLICY IF EXISTS "legal-referrals authenticated insert" ON storage.objects;
CREATE POLICY "legal-referrals authenticated insert" ON storage.objects AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((bucket_id = 'legal-referrals'::text));
DROP POLICY IF EXISTS "legal-referrals authenticated read" ON storage.objects;
CREATE POLICY "legal-referrals authenticated read" ON storage.objects AS PERMISSIVE FOR SELECT TO authenticated USING ((bucket_id = 'legal-referrals'::text));
DROP POLICY IF EXISTS "legal-referrals authenticated update" ON storage.objects;
CREATE POLICY "legal-referrals authenticated update" ON storage.objects AS PERMISSIVE FOR UPDATE TO authenticated USING ((bucket_id = 'legal-referrals'::text)) WITH CHECK ((bucket_id = 'legal-referrals'::text));
DROP POLICY IF EXISTS legal_docs_auth_delete ON storage.objects;
CREATE POLICY legal_docs_auth_delete ON storage.objects AS PERMISSIVE FOR DELETE TO authenticated USING ((bucket_id = 'legal-documents'::text));
DROP POLICY IF EXISTS legal_docs_auth_read ON storage.objects;
CREATE POLICY legal_docs_auth_read ON storage.objects AS PERMISSIVE FOR SELECT TO authenticated USING ((bucket_id = 'legal-documents'::text));
DROP POLICY IF EXISTS legal_docs_auth_update ON storage.objects;
CREATE POLICY legal_docs_auth_update ON storage.objects AS PERMISSIVE FOR UPDATE TO authenticated USING ((bucket_id = 'legal-documents'::text));
DROP POLICY IF EXISTS legal_docs_auth_write ON storage.objects;
CREATE POLICY legal_docs_auth_write ON storage.objects AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((bucket_id = 'legal-documents'::text));
