/**
 * INTERNAL AUDIT → OMNI-COMMS canonical communication catalogue (Wave 4).
 *
 * Single source of truth for every Internal Audit business moment that owes a
 * communication, the semantic recipient role that receives it, the channels the
 * Hub may use, and the token vocabulary the published contract enforces.
 *
 * This module is PURE DATA + PURE FUNCTIONS. It imports no Supabase client, no
 * React and no provider SDK. Internal Audit business code never chooses a
 * template, a channel, a sender or a provider — it only publishes facts.
 *
 * Canonical naming: INTERNAL_AUDIT.<ENTITY>.<ACTION> (three uppercase segments,
 * enforced by `omni_comms_event_definition_code_format_chk`).
 */

export const INTERNAL_AUDIT_MODULE_CODE = 'INTERNAL_AUDIT';

/** Semantic recipient roles. Never a persistence type, never a channel choice. */
export const IA_RECIPIENT_ROLES = [
  'lead_auditor',
  'head_of_audit',
  'qa_reviewer',
  'audit_committee',
  'action_owner',
  'auditee_contact',
  'department_head',
] as const;
export type IaRecipientRole = (typeof IA_RECIPIENT_ROLES)[number];

export type IaCommunicationClass =
  | 'transactional'
  | 'service'
  | 'operational'
  | 'legal_mandatory';

export type IaPriority = 'low' | 'normal' | 'high' | 'urgent';

export type IaChannel = 'email' | 'in_app';

export interface IaCommunicationEntry {
  /** Registered three-segment Omni-Comms event code. */
  eventCode: string;
  /** Durable business entity type (lowercase table-ish name). */
  entityType: string;
  /** Business lifecycle domain, used for grouping and reporting only. */
  domain:
    | 'PLAN'
    | 'ENGAGEMENT'
    | 'REQUEST'
    | 'FINDING'
    | 'REPORT'
    | 'ACTION'
    | 'FOLLOWUP';
  name: string;
  description: string;
  communicationClass: IaCommunicationClass;
  priority: IaPriority;
  /** Primary semantic recipient role for the obligation. */
  recipientRole: IaRecipientRole;
  /** Channels the Hub may consider. The Hub still decides what is sent. */
  channels: IaChannel[];
  /** Short human headline used as the email subject / in-app title stem. */
  headline: string;
  /** One-sentence body lead. */
  lead: string;
  /**
   * Business facts (beyond the always-present `subjectName` and `reference`)
   * the published contract requires.
   */
  facts: string[];
  /** Whether this event can legitimately recur for the same entity. */
  repeatable: boolean;
  /** In-app deep link pattern; `:id` is replaced with the entity id. */
  deepLink: string;
}

const BOTH: IaChannel[] = ['email', 'in_app'];
const APP_ONLY: IaChannel[] = ['in_app'];

export const INTERNAL_AUDIT_COMMUNICATION_CATALOGUE: IaCommunicationEntry[] = [
  // ── Annual plan ────────────────────────────────────────────────────────
  {
    eventCode: 'INTERNAL_AUDIT.PLAN.SUBMITTED',
    entityType: 'ia_annual_plan',
    domain: 'PLAN',
    name: 'Annual audit plan submitted for approval',
    description: 'The annual internal audit plan has been submitted into the approval workflow.',
    communicationClass: 'operational',
    priority: 'high',
    recipientRole: 'head_of_audit',
    channels: BOTH,
    headline: 'Annual audit plan {{payload.reference}} submitted for approval',
    lead: 'The annual internal audit plan has been submitted and is awaiting your approval.',
    facts: ['planYear', 'submittedOn', 'engagementCount'],
    repeatable: true,
    deepLink: '/audit/annual-plan/:id',
  },
  {
    eventCode: 'INTERNAL_AUDIT.PLAN.APPROVED',
    entityType: 'ia_annual_plan',
    domain: 'PLAN',
    name: 'Annual audit plan approved',
    description: 'The annual internal audit plan has been approved and is now executable.',
    communicationClass: 'operational',
    priority: 'high',
    recipientRole: 'lead_auditor',
    channels: BOTH,
    headline: 'Annual audit plan {{payload.reference}} approved',
    lead: 'The annual internal audit plan has been approved and engagements may now be launched.',
    facts: ['planYear', 'approvedOn', 'approvedBy'],
    repeatable: true,
    deepLink: '/audit/annual-plan/:id',
  },
  {
    eventCode: 'INTERNAL_AUDIT.PLAN.DISTRIBUTED',
    entityType: 'ia_annual_plan',
    domain: 'PLAN',
    name: 'Annual audit plan distributed',
    description:
      'A board-pack or final annual audit plan artifact has been distributed to a board, committee or oversight recipient with the governed PDF attached.',
    communicationClass: 'operational',
    priority: 'high',
    recipientRole: 'audit_committee',
    channels: BOTH,
    headline: 'Annual audit plan {{payload.reference}} distributed',
    lead: 'The annual internal audit plan artifact below has been distributed for your attention. The plan document is attached.',
    facts: [
      'planTitle',
      'planYear',
      'distributionPurpose',
      'artifactName',
      'artifactVersion',
      'distributedOn',
    ],
    repeatable: true,
    deepLink: '/audit/annual-plan/:id',
  },

  {
    eventCode: 'INTERNAL_AUDIT.PLAN.REJECTED',
    entityType: 'ia_annual_plan',
    domain: 'PLAN',
    name: 'Annual audit plan rejected',
    description: 'The annual internal audit plan was rejected by the approving authority.',
    communicationClass: 'operational',
    priority: 'high',
    recipientRole: 'lead_auditor',
    channels: BOTH,
    headline: 'Annual audit plan {{payload.reference}} rejected',
    lead: 'The annual internal audit plan was rejected and must be reworked before resubmission.',
    facts: ['planYear', 'decidedOn', 'decisionReason'],
    repeatable: true,
    deepLink: '/audit/annual-plan/:id',
  },
  {
    eventCode: 'INTERNAL_AUDIT.PLAN.REVISION_REQUESTED',
    entityType: 'ia_annual_plan',
    domain: 'PLAN',
    name: 'Annual audit plan revision requested',
    description: 'A material change requires the annual plan to be revised and re-approved.',
    communicationClass: 'operational',
    priority: 'normal',
    recipientRole: 'lead_auditor',
    channels: BOTH,
    headline: 'Revision requested for annual audit plan {{payload.reference}}',
    lead: 'A revision has been requested for the annual internal audit plan.',
    facts: ['planYear', 'requestedOn', 'revisionReason'],
    repeatable: true,
    deepLink: '/audit/annual-plan/:id',
  },
  {
    eventCode: 'INTERNAL_AUDIT.PLAN.CLOSED',
    entityType: 'ia_annual_plan',
    domain: 'PLAN',
    name: 'Annual audit plan closed',
    description: 'The annual internal audit plan has been closed for the plan year.',
    communicationClass: 'operational',
    priority: 'normal',
    recipientRole: 'head_of_audit',
    channels: BOTH,
    headline: 'Annual audit plan {{payload.reference}} closed',
    lead: 'The annual internal audit plan has been closed.',
    facts: ['planYear', 'closedOn', 'carriedForwardCount'],
    repeatable: false,
    deepLink: '/audit/annual-plan/:id',
  },
  {
    eventCode: 'INTERNAL_AUDIT.PLAN.TEAM_CONFLICT',
    entityType: 'ia_annual_plan',
    domain: 'PLAN',
    name: 'Audit team independence conflict detected',
    description: 'A team assignment breaches the independence or availability rules.',
    communicationClass: 'operational',
    priority: 'urgent',
    recipientRole: 'head_of_audit',
    channels: BOTH,
    headline: 'Independence conflict on audit plan {{payload.reference}}',
    lead: 'An independence or availability conflict was detected on an audit team assignment.',
    facts: ['planYear', 'conflictSummary', 'detectedOn'],
    repeatable: true,
    deepLink: '/audit/annual-plan/:id',
  },

  // ── Engagement ─────────────────────────────────────────────────────────
  {
    eventCode: 'INTERNAL_AUDIT.ENGAGEMENT.LAUNCHED',
    entityType: 'ia_audit_engagement',
    domain: 'ENGAGEMENT',
    name: 'Audit engagement launched',
    description: 'The engagement has passed launch readiness and fieldwork may begin.',
    communicationClass: 'operational',
    priority: 'high',
    recipientRole: 'lead_auditor',
    channels: BOTH,
    headline: 'Audit engagement {{payload.reference}} launched',
    lead: 'The audit engagement has been launched and is now in execution.',
    facts: ['engagementTitle', 'auditeeUnit', 'launchedOn', 'plannedEndDate'],
    repeatable: false,
    deepLink: '/audit/engagements/:id',
  },
  {
    eventCode: 'INTERNAL_AUDIT.ENGAGEMENT.INTIMATION_ISSUED',
    entityType: 'ia_audit_engagement',
    domain: 'ENGAGEMENT',
    name: 'Audit intimation issued to the auditee',
    description: 'Formal notice of the forthcoming audit has been issued to the auditee.',
    communicationClass: 'legal_mandatory',
    priority: 'high',
    recipientRole: 'auditee_contact',
    channels: BOTH,
    headline: 'Notice of internal audit — {{payload.engagementTitle}}',
    lead: 'This is formal notice that an internal audit of your area is scheduled.',
    facts: ['engagementTitle', 'auditeeUnit', 'scopeSummary', 'plannedStartDate', 'plannedEndDate'],
    repeatable: true,
    deepLink: '/audit/engagements/:id',
  },
  {
    eventCode: 'INTERNAL_AUDIT.ENGAGEMENT.ENTRANCE_MEETING',
    entityType: 'ia_audit_engagement',
    domain: 'ENGAGEMENT',
    name: 'Entrance meeting scheduled',
    description: 'The entrance meeting for the engagement has been scheduled.',
    communicationClass: 'service',
    priority: 'high',
    recipientRole: 'auditee_contact',
    channels: BOTH,
    headline: 'Entrance meeting for audit {{payload.reference}}',
    lead: 'An entrance meeting has been scheduled for the forthcoming internal audit.',
    facts: ['engagementTitle', 'meetingDateTime', 'meetingLocation'],
    repeatable: true,
    deepLink: '/audit/engagements/:id',
  },
  {
    eventCode: 'INTERNAL_AUDIT.ENGAGEMENT.EXIT_MEETING',
    entityType: 'ia_audit_engagement',
    domain: 'ENGAGEMENT',
    name: 'Exit meeting scheduled',
    description: 'The exit meeting for the engagement has been scheduled.',
    communicationClass: 'service',
    priority: 'high',
    recipientRole: 'auditee_contact',
    channels: BOTH,
    headline: 'Exit meeting for audit {{payload.reference}}',
    lead: 'An exit meeting has been scheduled to discuss the audit outcome.',
    facts: ['engagementTitle', 'meetingDateTime', 'meetingLocation'],
    repeatable: true,
    deepLink: '/audit/engagements/:id',
  },
  {
    eventCode: 'INTERNAL_AUDIT.ENGAGEMENT.FIELDWORK_COMPLETED',
    entityType: 'ia_audit_engagement',
    domain: 'ENGAGEMENT',
    name: 'Fieldwork completed',
    description: 'Fieldwork on the engagement has been concluded.',
    communicationClass: 'operational',
    priority: 'normal',
    recipientRole: 'head_of_audit',
    channels: BOTH,
    headline: 'Fieldwork completed for audit {{payload.reference}}',
    lead: 'Fieldwork has been completed and the engagement is moving to reporting.',
    facts: ['engagementTitle', 'completedOn', 'findingCount'],
    repeatable: false,
    deepLink: '/audit/engagements/:id',
  },
  {
    eventCode: 'INTERNAL_AUDIT.ENGAGEMENT.CLOSED',
    entityType: 'ia_audit_engagement',
    domain: 'ENGAGEMENT',
    name: 'Audit engagement closed',
    description: 'The engagement has satisfied all closure conditions and is closed.',
    communicationClass: 'operational',
    priority: 'normal',
    recipientRole: 'head_of_audit',
    channels: BOTH,
    headline: 'Audit engagement {{payload.reference}} closed',
    lead: 'The audit engagement has been closed.',
    facts: ['engagementTitle', 'closedOn', 'openActionCount'],
    repeatable: false,
    deepLink: '/audit/engagements/:id',
  },

  // ── Information requests (PBC) ─────────────────────────────────────────
  {
    eventCode: 'INTERNAL_AUDIT.REQUEST.ISSUED',
    entityType: 'ia_information_request',
    domain: 'REQUEST',
    name: 'Information request issued',
    description: 'An audit information/document request has been issued to the auditee.',
    communicationClass: 'transactional',
    priority: 'high',
    recipientRole: 'auditee_contact',
    channels: BOTH,
    headline: 'Information requested for audit {{payload.reference}}',
    lead: 'The internal audit team requires the following information.',
    facts: ['requestSummary', 'dueDate', 'engagementTitle'],
    repeatable: true,
    deepLink: '/audit/engagements/:id',
  },
  {
    eventCode: 'INTERNAL_AUDIT.REQUEST.REMINDER',
    entityType: 'ia_information_request',
    domain: 'REQUEST',
    name: 'Information request reminder',
    description: 'A reminder that an outstanding information request is approaching its due date.',
    communicationClass: 'transactional',
    priority: 'high',
    recipientRole: 'auditee_contact',
    channels: BOTH,
    headline: 'Reminder: information outstanding for audit {{payload.reference}}',
    lead: 'The following information request is still outstanding.',
    facts: ['requestSummary', 'dueDate', 'daysRemaining'],
    repeatable: true,
    deepLink: '/audit/engagements/:id',
  },
  {
    eventCode: 'INTERNAL_AUDIT.REQUEST.OVERDUE',
    entityType: 'ia_information_request',
    domain: 'REQUEST',
    name: 'Information request overdue',
    description: 'An information request has passed its due date without a complete response.',
    communicationClass: 'transactional',
    priority: 'urgent',
    recipientRole: 'auditee_contact',
    channels: BOTH,
    headline: 'Overdue: information request for audit {{payload.reference}}',
    lead: 'An information request required by the internal audit team is now overdue.',
    facts: ['requestSummary', 'dueDate', 'daysOverdue'],
    repeatable: true,
    deepLink: '/audit/engagements/:id',
  },
  {
    eventCode: 'INTERNAL_AUDIT.REQUEST.FULFILLED',
    entityType: 'ia_information_request',
    domain: 'REQUEST',
    name: 'Information request fulfilled',
    description:
      'Every outstanding information request for the engagement has been received by the audit team.',
    communicationClass: 'service',
    priority: 'normal',
    recipientRole: 'auditee_contact',
    channels: BOTH,
    headline: 'All requested information received for audit {{payload.reference}}',
    lead: 'The internal audit team has received all outstanding information requests.',
    facts: ['requestSummary', 'engagementTitle'],
    repeatable: true,
    deepLink: '/audit/engagements/:id',
  },



  // ── Findings ───────────────────────────────────────────────────────────
  {
    eventCode: 'INTERNAL_AUDIT.FINDING.RAISED',
    entityType: 'ia_audit_finding',
    domain: 'FINDING',
    name: 'Audit finding raised',
    description: 'A new audit finding has been recorded against the engagement.',
    communicationClass: 'operational',
    priority: 'high',
    recipientRole: 'lead_auditor',
    channels: BOTH,
    headline: 'Finding {{payload.reference}} raised',
    lead: 'A new audit finding has been raised.',
    facts: ['findingTitle', 'severity', 'engagementTitle', 'raisedOn'],
    repeatable: false,
    deepLink: '/audit/engagements/:id',
  },
  {
    eventCode: 'INTERNAL_AUDIT.FINDING.SEVERITY_CHANGED',
    entityType: 'ia_audit_finding',
    domain: 'FINDING',
    name: 'Finding severity changed',
    description: 'The severity rating of an audit finding has been changed.',
    communicationClass: 'operational',
    priority: 'normal',
    recipientRole: 'head_of_audit',
    channels: BOTH,
    headline: 'Severity changed on finding {{payload.reference}}',
    lead: 'The severity of an audit finding has been reassessed.',
    facts: ['findingTitle', 'previousSeverity', 'severity', 'changeReason'],
    repeatable: true,
    deepLink: '/audit/engagements/:id',
  },
  {
    eventCode: 'INTERNAL_AUDIT.FINDING.RESPONSE_REQUESTED',
    entityType: 'ia_audit_finding',
    domain: 'FINDING',
    name: 'Management response requested',
    description: 'A management response has been requested for an audit finding.',
    communicationClass: 'transactional',
    priority: 'high',
    recipientRole: 'department_head',
    channels: BOTH,
    headline: 'Management response required for finding {{payload.reference}}',
    lead: 'A management response is required for the following audit finding.',
    facts: ['findingTitle', 'severity', 'dueDate'],
    repeatable: true,
    deepLink: '/audit/engagements/:id',
  },
  {
    eventCode: 'INTERNAL_AUDIT.FINDING.RESPONSE_SUBMITTED',
    entityType: 'ia_audit_finding',
    domain: 'FINDING',
    name: 'Management response submitted',
    description: 'Management has submitted its response to an audit finding.',
    communicationClass: 'operational',
    priority: 'high',
    recipientRole: 'lead_auditor',
    channels: BOTH,
    headline: 'Management response submitted for finding {{payload.reference}}',
    lead: 'A management response has been submitted and awaits audit review.',
    facts: ['findingTitle', 'submittedOn', 'responseSummary'],
    repeatable: true,
    deepLink: '/audit/engagements/:id',
  },
  {
    eventCode: 'INTERNAL_AUDIT.FINDING.RESPONSE_ACCEPTED',
    entityType: 'ia_audit_finding',
    domain: 'FINDING',
    name: 'Management response accepted',
    description: 'Internal Audit accepted the management response to a finding.',
    communicationClass: 'operational',
    priority: 'normal',
    recipientRole: 'department_head',
    channels: BOTH,
    headline: 'Management response accepted for finding {{payload.reference}}',
    lead: 'Internal Audit has accepted the management response.',
    facts: ['findingTitle', 'decidedOn', 'reviewerComment'],
    repeatable: true,
    deepLink: '/audit/engagements/:id',
  },
  {
    eventCode: 'INTERNAL_AUDIT.FINDING.RESPONSE_REJECTED',
    entityType: 'ia_audit_finding',
    domain: 'FINDING',
    name: 'Management response returned',
    description: 'Internal Audit returned the management response for rework.',
    communicationClass: 'transactional',
    priority: 'high',
    recipientRole: 'department_head',
    channels: BOTH,
    headline: 'Management response returned for finding {{payload.reference}}',
    lead: 'Internal Audit has returned the management response for rework.',
    facts: ['findingTitle', 'decidedOn', 'reviewerComment', 'dueDate'],
    repeatable: true,
    deepLink: '/audit/engagements/:id',
  },

  // ── Reporting ──────────────────────────────────────────────────────────
  {
    eventCode: 'INTERNAL_AUDIT.REPORT.DRAFT_CIRCULATED',
    entityType: 'ia_audit_report',
    domain: 'REPORT',
    name: 'Draft audit report circulated',
    description: 'A draft audit report version has been circulated for comment.',
    communicationClass: 'operational',
    priority: 'high',
    recipientRole: 'department_head',
    channels: BOTH,
    headline: 'Draft audit report {{payload.reference}} circulated',
    lead: 'A draft internal audit report has been circulated for your comment.',
    facts: ['engagementTitle', 'versionNumber', 'commentDueDate'],
    repeatable: true,
    deepLink: '/audit/engagements/:id',
  },
  {
    eventCode: 'INTERNAL_AUDIT.REPORT.QA_REQUESTED',
    entityType: 'ia_audit_report',
    domain: 'REPORT',
    name: 'Quality review requested',
    description: 'A quality assurance review has been requested on the engagement report.',
    communicationClass: 'operational',
    priority: 'high',
    recipientRole: 'qa_reviewer',
    channels: BOTH,
    headline: 'Quality review requested for audit {{payload.reference}}',
    lead: 'A quality assurance review has been assigned to you.',
    facts: ['engagementTitle', 'requestedOn', 'dueDate'],
    repeatable: true,
    deepLink: '/audit/engagements/:id',
  },
  {
    eventCode: 'INTERNAL_AUDIT.REPORT.QA_CLEARED',
    entityType: 'ia_audit_report',
    domain: 'REPORT',
    name: 'Quality review concluded',
    description: 'The quality assurance review has been concluded.',
    communicationClass: 'operational',
    priority: 'normal',
    recipientRole: 'lead_auditor',
    channels: BOTH,
    headline: 'Quality review concluded for audit {{payload.reference}}',
    lead: 'The quality assurance review has been concluded.',
    facts: ['engagementTitle', 'concludedOn', 'qaOutcome'],
    repeatable: true,
    deepLink: '/audit/engagements/:id',
  },
  {
    eventCode: 'INTERNAL_AUDIT.REPORT.ISSUED',
    entityType: 'ia_audit_report',
    domain: 'REPORT',
    name: 'Final audit report issued',
    description: 'The final audit report has been formally issued.',
    communicationClass: 'legal_mandatory',
    priority: 'urgent',
    recipientRole: 'department_head',
    channels: BOTH,
    headline: 'Final internal audit report {{payload.reference}} issued',
    lead: 'The final internal audit report has been issued.',
    facts: ['engagementTitle', 'issuedOn', 'versionNumber', 'overallOpinion'],
    repeatable: true,
    deepLink: '/audit/engagements/:id',
  },

  // ── Corrective actions ─────────────────────────────────────────────────
  {
    eventCode: 'INTERNAL_AUDIT.ACTION.ASSIGNED',
    entityType: 'ia_action_tracking',
    domain: 'ACTION',
    name: 'Corrective action assigned',
    description: 'A corrective action has been assigned to an action owner.',
    communicationClass: 'transactional',
    priority: 'high',
    recipientRole: 'action_owner',
    channels: BOTH,
    headline: 'Corrective action {{payload.reference}} assigned to you',
    lead: 'A corrective action arising from an internal audit has been assigned to you.',
    facts: ['actionTitle', 'severity', 'targetDate', 'engagementTitle'],
    repeatable: true,
    deepLink: '/audit/actions/:id',
  },
  {
    eventCode: 'INTERNAL_AUDIT.ACTION.DUE_SOON',
    entityType: 'ia_action_tracking',
    domain: 'ACTION',
    name: 'Corrective action due soon',
    description: 'A corrective action is approaching its agreed target date.',
    communicationClass: 'transactional',
    priority: 'high',
    recipientRole: 'action_owner',
    channels: BOTH,
    headline: 'Corrective action {{payload.reference}} is due soon',
    lead: 'A corrective action assigned to you is approaching its target date.',
    facts: ['actionTitle', 'targetDate', 'daysRemaining'],
    repeatable: true,
    deepLink: '/audit/actions/:id',
  },
  {
    eventCode: 'INTERNAL_AUDIT.ACTION.OVERDUE',
    entityType: 'ia_action_tracking',
    domain: 'ACTION',
    name: 'Corrective action overdue',
    description: 'A corrective action has passed its agreed target date.',
    communicationClass: 'transactional',
    priority: 'urgent',
    recipientRole: 'action_owner',
    channels: BOTH,
    headline: 'Corrective action {{payload.reference}} is overdue',
    lead: 'A corrective action assigned to you is now overdue.',
    facts: ['actionTitle', 'targetDate', 'daysOverdue'],
    repeatable: true,
    deepLink: '/audit/actions/:id',
  },
  {
    eventCode: 'INTERNAL_AUDIT.ACTION.ESCALATED',
    entityType: 'ia_action_tracking',
    domain: 'ACTION',
    name: 'Corrective action escalated',
    description: 'An overdue corrective action has been escalated to audit leadership.',
    communicationClass: 'operational',
    priority: 'urgent',
    recipientRole: 'head_of_audit',
    channels: BOTH,
    headline: 'Escalation: corrective action {{payload.reference}} overdue',
    lead: 'A corrective action remains overdue and has been escalated.',
    facts: ['actionTitle', 'targetDate', 'daysOverdue', 'ownerName'],
    repeatable: true,
    deepLink: '/audit/actions/:id',
  },
  {
    eventCode: 'INTERNAL_AUDIT.ACTION.PROGRESS_RECORDED',
    entityType: 'ia_action_tracking',
    domain: 'ACTION',
    name: 'Action progress recorded',
    description: 'The action owner has recorded progress against a corrective action.',
    communicationClass: 'operational',
    priority: 'normal',
    recipientRole: 'lead_auditor',
    channels: APP_ONLY,
    headline: 'Progress recorded on action {{payload.reference}}',
    lead: 'Progress has been recorded against a corrective action.',
    facts: ['actionTitle', 'progressPercent', 'progressNote'],
    repeatable: true,
    deepLink: '/audit/actions/:id',
  },
  {
    eventCode: 'INTERNAL_AUDIT.ACTION.COMPLETION_SUBMITTED',
    entityType: 'ia_action_tracking',
    domain: 'ACTION',
    name: 'Action completion submitted',
    description: 'Management has submitted a corrective action as complete, awaiting verification.',
    communicationClass: 'transactional',
    priority: 'high',
    recipientRole: 'lead_auditor',
    channels: BOTH,
    headline: 'Completion submitted for action {{payload.reference}}',
    lead: 'A corrective action has been submitted as complete and awaits audit verification.',
    facts: ['actionTitle', 'submittedOn', 'completionSummary'],
    repeatable: true,
    deepLink: '/audit/actions/:id',
  },
  {
    eventCode: 'INTERNAL_AUDIT.ACTION.VERIFIED',
    entityType: 'ia_action_tracking',
    domain: 'ACTION',
    name: 'Action verified by Internal Audit',
    description: 'Internal Audit verified that the corrective action is effective.',
    communicationClass: 'transactional',
    priority: 'normal',
    recipientRole: 'action_owner',
    channels: BOTH,
    headline: 'Corrective action {{payload.reference}} verified',
    lead: 'Internal Audit has verified your corrective action as effective.',
    facts: ['actionTitle', 'verifiedOn', 'verificationComment'],
    repeatable: true,
    deepLink: '/audit/actions/:id',
  },
  {
    eventCode: 'INTERNAL_AUDIT.ACTION.VERIFICATION_REJECTED',
    entityType: 'ia_action_tracking',
    domain: 'ACTION',
    name: 'Action verification rejected',
    description: 'Internal Audit rejected the claimed completion of a corrective action.',
    communicationClass: 'transactional',
    priority: 'urgent',
    recipientRole: 'action_owner',
    channels: BOTH,
    headline: 'Verification rejected for action {{payload.reference}}',
    lead: 'Internal Audit could not verify the completion of your corrective action.',
    facts: ['actionTitle', 'decidedOn', 'rejectionReason', 'targetDate'],
    repeatable: true,
    deepLink: '/audit/actions/:id',
  },
  {
    eventCode: 'INTERNAL_AUDIT.ACTION.EXTENSION_REQUESTED',
    entityType: 'ia_action_tracking',
    domain: 'ACTION',
    name: 'Action extension requested',
    description: 'An extension to the agreed target date has been requested.',
    communicationClass: 'transactional',
    priority: 'high',
    recipientRole: 'head_of_audit',
    channels: BOTH,
    headline: 'Extension requested for action {{payload.reference}}',
    lead: 'An extension to a corrective action target date has been requested.',
    facts: ['actionTitle', 'targetDate', 'requestedDate', 'extensionReason'],
    repeatable: true,
    deepLink: '/audit/actions/:id',
  },
  {
    eventCode: 'INTERNAL_AUDIT.ACTION.EXTENSION_DECIDED',
    entityType: 'ia_action_tracking',
    domain: 'ACTION',
    name: 'Action extension decided',
    description: 'A decision has been taken on a requested target-date extension.',
    communicationClass: 'transactional',
    priority: 'high',
    recipientRole: 'action_owner',
    channels: BOTH,
    headline: 'Extension decision for action {{payload.reference}}',
    lead: 'A decision has been made on your requested extension.',
    facts: ['actionTitle', 'extensionOutcome', 'targetDate', 'decisionReason'],
    repeatable: true,
    deepLink: '/audit/actions/:id',
  },
  {
    eventCode: 'INTERNAL_AUDIT.ACTION.CLOSED',
    entityType: 'ia_action_tracking',
    domain: 'ACTION',
    name: 'Corrective action closed',
    description: 'A corrective action has been formally closed.',
    communicationClass: 'operational',
    priority: 'normal',
    recipientRole: 'action_owner',
    channels: BOTH,
    headline: 'Corrective action {{payload.reference}} closed',
    lead: 'A corrective action has been formally closed.',
    facts: ['actionTitle', 'closedOn', 'closureBasis'],
    repeatable: true,
    deepLink: '/audit/actions/:id',
  },

  // ── Follow-up and continuity ───────────────────────────────────────────
  {
    eventCode: 'INTERNAL_AUDIT.FOLLOWUP.SCHEDULED',
    entityType: 'ia_followup',
    domain: 'FOLLOWUP',
    name: 'Follow-up review scheduled',
    description: 'A follow-up review has been scheduled for a closed engagement or action.',
    communicationClass: 'operational',
    priority: 'normal',
    recipientRole: 'lead_auditor',
    channels: BOTH,
    headline: 'Follow-up review scheduled — {{payload.reference}}',
    lead: 'A follow-up review has been scheduled.',
    facts: ['followupSubject', 'scheduledFor', 'engagementTitle'],
    repeatable: true,
    deepLink: '/audit/follow-up',
  },
  {
    eventCode: 'INTERNAL_AUDIT.FOLLOWUP.OUTCOME_RECORDED',
    entityType: 'ia_followup',
    domain: 'FOLLOWUP',
    name: 'Follow-up outcome recorded',
    description: 'The outcome of a follow-up review has been recorded.',
    communicationClass: 'operational',
    priority: 'normal',
    recipientRole: 'head_of_audit',
    channels: BOTH,
    headline: 'Follow-up outcome recorded — {{payload.reference}}',
    lead: 'The outcome of a follow-up review has been recorded.',
    facts: ['followupSubject', 'recordedOn', 'followupOutcome'],
    repeatable: true,
    deepLink: '/audit/follow-up',
  },
  {
    eventCode: 'INTERNAL_AUDIT.FOLLOWUP.CARRIED_FORWARD',
    entityType: 'ia_followup',
    domain: 'FOLLOWUP',
    name: 'Open matter carried forward',
    description: 'An open matter has been carried forward into the next plan year.',
    communicationClass: 'operational',
    priority: 'normal',
    recipientRole: 'head_of_audit',
    channels: BOTH,
    headline: 'Matter {{payload.reference}} carried forward',
    lead: 'An open audit matter has been carried forward into the next plan year.',
    facts: ['followupSubject', 'fromPlanYear', 'toPlanYear'],
    repeatable: true,
    deepLink: '/audit/follow-up',
  },
];

/** Always-present tokens supplied by the producer for every IA event. */
export const IA_BASE_TOKENS = ['subjectName', 'reference'] as const;

const BY_CODE = new Map<string, IaCommunicationEntry>(
  INTERNAL_AUDIT_COMMUNICATION_CATALOGUE.map((entry) => [entry.eventCode, entry]),
);

export function internalAuditEntry(eventCode: string): IaCommunicationEntry | null {
  return BY_CODE.get(String(eventCode ?? '').trim().toUpperCase()) ?? null;
}

/** Full token vocabulary (base tokens + business facts) for an event. */
export function internalAuditTokens(entry: IaCommunicationEntry): string[] {
  return [...IA_BASE_TOKENS, ...entry.facts];
}

/** Template family code (<= 60 chars) for an event. */
export function internalAuditFamilyCode(entry: IaCommunicationEntry): string {
  return `ia_${entry.eventCode.toLowerCase().replace(/\./g, '_')}`.slice(0, 60);
}

export const INTERNAL_AUDIT_EVENT_CODES = INTERNAL_AUDIT_COMMUNICATION_CATALOGUE.map(
  (entry) => entry.eventCode,
);
