/**
 * Benefits → Omni-Comms email template specifications.
 *
 * One specification per Email-capable Benefits event in
 * `benefitsCommunicationCatalogue.ts`. Each specification composes into a
 * complete, professional letter (see `benefitsEmailComposer.ts`).
 *
 * Pure data. No Supabase client, no React, no provider SDK.
 */
import type { BenefitsEmailSpec } from './benefitsEmailComposer';

const t = (label: string, token: string) => ({ label, token });

export const BENEFITS_EMAIL_SPECS: BenefitsEmailSpec[] = [
  // ------------------------------------------------------------------ CLAIM
  {
    eventCode: 'BENEFITS.CLAIM.SUBMITTED',
    templateFamily: 'BENEFITS_CLAIM_SUBMITTED',
    recipientRole: 'claimant',
    name: 'Benefit claim received',
    description:
      'Acknowledges a benefit claim the moment it is submitted, so the claimant has written proof of lodgement.',
    communicationClass: 'transactional',
    priority: 'normal',
    subject: 'We have received your {{payload.claimType}} claim {{payload.reference}}',
    preheader: 'Your claim has been lodged and is waiting to be assessed.',
    headline: 'Your benefit claim has been received',
    intro: [
      'Thank you for submitting your claim to the Social Security Board. This message confirms that your claim has been lodged and recorded on your record.',
      'Your claim will now be checked for completeness and assessed against the qualifying conditions for the benefit you applied for.',
    ],
    details: [
      t('Claim reference', 'reference'),
      t('Benefit type', 'claimType'),
      t('Date received', 'submittedOn'),
      t('Current status', 'claimStatus'),
    ],
    nextSteps: [
      'An officer will review the documents supplied with your claim.',
      'If anything further is needed, we will write to you and tell you exactly what to send and by when.',
      'You will receive a written decision once the assessment is complete.',
    ],
    closing: 'You do not need to do anything further at this stage.',
  },
  {
    eventCode: 'BENEFITS.CLAIM.WITHDRAWN',
    templateFamily: 'BENEFITS_CLAIM_WITHDRAWN',
    recipientRole: 'claimant',
    name: 'Benefit claim withdrawn',
    description:
      'Confirms that a claim has been withdrawn at the claimant’s request and that no decision will be issued.',
    communicationClass: 'transactional',
    priority: 'normal',
    subject: 'Your claim {{payload.reference}} has been withdrawn',
    preheader: 'We have closed your claim at your request.',
    headline: 'Your claim has been withdrawn',
    intro: [
      'We have recorded the withdrawal of your benefit claim. No assessment will continue and no decision will be issued on this claim.',
    ],
    details: [
      t('Claim reference', 'reference'),
      t('Benefit type', 'claimType'),
      t('Withdrawn on', 'withdrawnOn'),
      t('Reason recorded', 'withdrawalReason'),
    ],
    nextSteps: [
      'Your record will show this claim as withdrawn.',
      'You may submit a new claim at any time if your circumstances qualify.',
    ],
    notice:
      'Withdrawing a claim does not affect any other claim or award you hold with the Board.',
  },
  {
    eventCode: 'BENEFITS.CLAIM.CORRECTION.COMPLETED',
    templateFamily: 'BENEFITS_CLAIM_CORRECTION_COMPLETED',
    recipientRole: 'claimant',
    name: 'Benefit claim correction completed',
    description:
      'Tells the claimant that a correction to their claim record has been applied and what changed.',
    communicationClass: 'transactional',
    priority: 'normal',
    subject: 'A correction was applied to your claim {{payload.reference}}',
    preheader: 'Your claim record has been corrected.',
    headline: 'Correction applied to your claim',
    intro: [
      'A correction has been completed on your benefit claim. We are writing so that you have a record of exactly what was changed.',
    ],
    details: [
      t('Claim reference', 'reference'),
      t('Corrected on', 'correctedOn'),
      t('What changed', 'correctionSummary'),
      t('Reason for correction', 'correctionReason'),
    ],
    nextSteps: [
      'Check the corrected details above.',
      'If any detail is still wrong, contact us and quote your claim reference.',
    ],
  },

  // --------------------------------------------------------------- EVIDENCE
  {
    eventCode: 'BENEFITS.CLAIM.EVIDENCE.REQUESTED',
    templateFamily: 'BENEFITS_CLAIM_EVIDENCE_REQUESTED',
    recipientRole: 'claimant',
    name: 'Evidence requested for a claim',
    description:
      'Formally requests outstanding documents needed before a claim can be decided, with a deadline.',
    communicationClass: 'transactional',
    priority: 'high',
    subject: 'Action needed: documents for your claim {{payload.reference}}',
    preheader: 'We need documents from you before your claim can be decided.',
    headline: 'We need some documents from you',
    intro: [
      'We cannot complete the assessment of your claim until we receive the items listed below.',
      'Please send everything together, and make sure the copies are clear and complete.',
    ],
    details: [
      t('Claim reference', 'reference'),
      t('Documents required', 'evidenceRequested'),
      t('Send by', 'dueDate'),
      t('How to send', 'submissionChannel'),
    ],
    nextSteps: [
      'Gather each item listed above.',
      'Submit them using the method shown before the due date.',
      'We will write to you again once the documents have been checked.',
    ],
    notice:
      'If we do not receive the documents by {{payload.dueDate}}, your claim may be decided on the information already held, which could result in it being disallowed.',
  },
  {
    eventCode: 'BENEFITS.CLAIM.EVIDENCE.RECEIVED',
    templateFamily: 'BENEFITS_CLAIM_EVIDENCE_RECEIVED',
    recipientRole: 'claimant',
    name: 'Evidence received for a claim',
    description: 'Confirms receipt of documents supplied for a claim.',
    communicationClass: 'transactional',
    priority: 'normal',
    subject: 'We have received your documents for claim {{payload.reference}}',
    preheader: 'Your documents are with us and are being checked.',
    headline: 'Your documents have been received',
    intro: [
      'Thank you. The documents you sent for your claim have been received and attached to your record.',
    ],
    details: [
      t('Claim reference', 'reference'),
      t('Documents received', 'evidenceReceived'),
      t('Received on', 'receivedOn'),
    ],
    nextSteps: [
      'An officer will check that each document meets the requirement.',
      'If anything is unclear or incomplete we will contact you.',
    ],
    closing: 'No further action is needed from you right now.',
  },
  {
    eventCode: 'BENEFITS.CLAIM.EVIDENCE.RESUBMISSION_REQUIRED',
    templateFamily: 'BENEFITS_CLAIM_EVIDENCE_RESUBMISSION_REQUIRED',
    recipientRole: 'claimant',
    name: 'Evidence must be resubmitted',
    description:
      'Explains why supplied evidence was not accepted and what must be sent again.',
    communicationClass: 'transactional',
    priority: 'high',
    subject: 'Please resend documents for claim {{payload.reference}}',
    preheader: 'One or more documents could not be accepted.',
    headline: 'We need you to send a document again',
    intro: [
      'We checked the documents you sent for your claim. Unfortunately one or more of them could not be accepted in the form supplied.',
    ],
    details: [
      t('Claim reference', 'reference'),
      t('Item to resend', 'evidenceRequested'),
      t('Why it was not accepted', 'rejectionReason'),
      t('Resend by', 'dueDate'),
    ],
    nextSteps: [
      'Obtain a clear, complete copy of the item shown above.',
      'Send it to us before the date shown.',
      'We will confirm as soon as the replacement has been accepted.',
    ],
    notice:
      'Your claim remains open while we wait, but it cannot be decided until the outstanding item is accepted.',
  },

  // ---------------------------------------------------------- DETERMINATION
  {
    eventCode: 'BENEFITS.CLAIM.APPROVED',
    templateFamily: 'BENEFITS_CLAIM_APPROVED',
    recipientRole: 'claimant',
    name: 'Benefit claim approved',
    description:
      'Issues the formal decision that a claim has been approved, with the award terms.',
    communicationClass: 'legal_mandatory',
    priority: 'high',
    subject: 'Your claim {{payload.reference}} has been approved',
    preheader: 'Your benefit claim has been approved.',
    headline: 'Your benefit claim has been approved',
    intro: [
      'We have completed the assessment of your claim and are pleased to tell you that it has been approved.',
      'The terms of your award are set out below. Please check them carefully and keep this notice for your records.',
    ],
    details: [
      t('Claim reference', 'reference'),
      t('Benefit type', 'claimType'),
      t('Decision date', 'decisionDate'),
      t('Award summary', 'awardSummary'),
      t('Weekly / monthly rate', 'benefitRate'),
      t('Effective from', 'effectiveFrom'),
    ],
    nextSteps: [
      'Your award will be set up for payment under the schedule shown on your award notice.',
      'Tell us immediately if any of your circumstances change, as this can affect your entitlement.',
    ],
    notice:
      'If you disagree with any part of this decision you may appeal. An appeal must normally be lodged within the statutory period stated in your decision notice.',
  },
  {
    eventCode: 'BENEFITS.CLAIM.DISALLOWED',
    templateFamily: 'BENEFITS_CLAIM_DISALLOWED',
    recipientRole: 'claimant',
    name: 'Benefit claim disallowed',
    description:
      'Issues the formal decision that a claim has been disallowed, the reason, and appeal rights.',
    communicationClass: 'legal_mandatory',
    priority: 'high',
    subject: 'Decision on your claim {{payload.reference}}',
    preheader: 'A decision has been made on your benefit claim.',
    headline: 'Decision on your benefit claim',
    intro: [
      'We have completed the assessment of your claim. After considering the information held, your claim has been disallowed.',
      'The reason for this decision is set out below.',
    ],
    details: [
      t('Claim reference', 'reference'),
      t('Benefit type', 'claimType'),
      t('Decision date', 'decisionDate'),
      t('Reason for the decision', 'decisionReason'),
      t('Legal provision applied', 'legalBasis'),
    ],
    nextSteps: [
      'Read the reason given above carefully.',
      'If you have information that was not available when the decision was made, you may send it to us.',
      'If you disagree with the decision, you may lodge an appeal.',
    ],
    notice:
      'You have the right to appeal this decision. Your appeal must be lodged in writing within the statutory period, quoting reference {{payload.reference}}.',
  },

  // ------------------------------------------------------------------ AWARD
  {
    eventCode: 'BENEFITS.AWARD.CREATED',
    templateFamily: 'BENEFITS_AWARD_CREATED',
    recipientRole: 'beneficiary',
    name: 'Benefit award created',
    description: 'Notifies the beneficiary that an award has been established.',
    communicationClass: 'legal_mandatory',
    priority: 'high',
    subject: 'Your benefit award {{payload.reference}} has been set up',
    preheader: 'Your award has been created and payments will follow the schedule shown.',
    headline: 'Your benefit award has been set up',
    intro: [
      'Your benefit award has been created. This notice sets out the rate, the period covered and how you will be paid.',
    ],
    details: [
      t('Award reference', 'reference'),
      t('Benefit type', 'benefitType'),
      t('Rate', 'benefitRate'),
      t('Effective from', 'effectiveFrom'),
      t('Payment method', 'paymentMethod'),
      t('Payment frequency', 'paymentFrequency'),
    ],
    nextSteps: [
      'Check that your payment details are correct.',
      'Keep this notice; you may need it when dealing with other agencies.',
      'Report any change in your circumstances without delay.',
    ],
    notice:
      'Payments depend on you continuing to meet the conditions of the award. Failure to report a change may create an overpayment that must be repaid.',
  },
  {
    eventCode: 'BENEFITS.AWARD.ADJUSTED',
    templateFamily: 'BENEFITS_AWARD_ADJUSTED',
    recipientRole: 'beneficiary',
    name: 'Benefit award adjusted',
    description: 'Explains an adjustment to an existing award and its effective date.',
    communicationClass: 'legal_mandatory',
    priority: 'high',
    subject: 'Your benefit award {{payload.reference}} has changed',
    preheader: 'The rate or terms of your award have been adjusted.',
    headline: 'Your benefit award has been adjusted',
    intro: [
      'The terms of your benefit award have been adjusted. The change and the date it takes effect are shown below.',
    ],
    details: [
      t('Award reference', 'reference'),
      t('Previous rate', 'previousRate'),
      t('New rate', 'benefitRate'),
      t('Effective from', 'effectiveFrom'),
      t('Reason for the change', 'adjustmentReason'),
    ],
    nextSteps: [
      'Check the new rate and effective date.',
      'Your next payment will reflect the adjusted amount.',
      'Contact us if you believe the adjustment is incorrect.',
    ],
    notice: 'You may appeal an adjustment you disagree with.',
  },
  {
    eventCode: 'BENEFITS.AWARD.TERMINATED',
    templateFamily: 'BENEFITS_AWARD_TERMINATED',
    recipientRole: 'beneficiary',
    name: 'Benefit award terminated',
    description: 'Notifies the beneficiary that an award has ended, with the reason.',
    communicationClass: 'legal_mandatory',
    priority: 'high',
    subject: 'Your benefit award {{payload.reference}} has ended',
    preheader: 'Your award has been terminated from the date shown.',
    headline: 'Your benefit award has ended',
    intro: [
      'Your benefit award has been terminated. No further payments will be made after the date shown below.',
    ],
    details: [
      t('Award reference', 'reference'),
      t('Benefit type', 'benefitType'),
      t('Last day of entitlement', 'terminationDate'),
      t('Reason', 'terminationReason'),
      t('Final payment', 'finalPaymentSummary'),
    ],
    nextSteps: [
      'Check whether any final payment is due to you.',
      'If you believe you still qualify, contact us with supporting evidence.',
    ],
    notice: 'You have the right to appeal this decision within the statutory period.',
  },
  {
    eventCode: 'BENEFITS.AWARD.UPRATED',
    templateFamily: 'BENEFITS_AWARD_UPRATED',
    recipientRole: 'beneficiary',
    name: 'Benefit award uprated',
    description: 'Notifies the beneficiary of a statutory uprating of their award.',
    communicationClass: 'transactional',
    priority: 'normal',
    subject: 'Your benefit rate is changing from {{payload.effectiveFrom}}',
    preheader: 'Your award has been uprated.',
    headline: 'Your benefit has been uprated',
    intro: [
      'Following a review of benefit rates, your award has been uprated. Your new rate is shown below.',
    ],
    details: [
      t('Award reference', 'reference'),
      t('Previous rate', 'previousRate'),
      t('New rate', 'benefitRate'),
      t('Effective from', 'effectiveFrom'),
      t('Uprating exercise', 'upratingCycle'),
    ],
    nextSteps: [
      'No action is needed from you.',
      'Your payments will change automatically from the effective date.',
    ],
  },

  // -------------------------------------------------- SUSPENSION / REINSTATE
  {
    eventCode: 'BENEFITS.AWARD.SUSPENSION.EXECUTED',
    templateFamily: 'BENEFITS_AWARD_SUSPENSION_EXECUTED',
    recipientRole: 'beneficiary',
    name: 'Benefit award suspended',
    description:
      'Notifies the beneficiary that payments have been suspended, why, and how to resolve it.',
    communicationClass: 'legal_mandatory',
    priority: 'urgent',
    subject: 'Important: payments on award {{payload.reference}} are suspended',
    preheader: 'Your benefit payments have been suspended.',
    headline: 'Your benefit payments have been suspended',
    intro: [
      'Payments on your benefit award have been suspended. This means no further payment will be released until the matter below is resolved.',
    ],
    details: [
      t('Award reference', 'reference'),
      t('Suspended from', 'suspensionFrom'),
      t('Reason', 'suspensionReason'),
      t('What is required to lift it', 'resolutionRequirement'),
    ],
    nextSteps: [
      'Read the requirement shown above.',
      'Provide what is needed as soon as possible so that payments can resume.',
      'Contact us if you believe the suspension is a mistake.',
    ],
    notice:
      'A suspension is not a termination. If the requirement is met, payments can be reinstated, including any amount withheld while suspended.',
  },
  {
    eventCode: 'BENEFITS.AWARD.REINSTATEMENT.EXECUTED',
    templateFamily: 'BENEFITS_AWARD_REINSTATEMENT_EXECUTED',
    recipientRole: 'beneficiary',
    name: 'Benefit award reinstated',
    description: 'Confirms that a suspended award has been reinstated.',
    communicationClass: 'transactional',
    priority: 'high',
    subject: 'Good news: payments on award {{payload.reference}} have resumed',
    preheader: 'Your benefit payments have been reinstated.',
    headline: 'Your benefit payments have resumed',
    intro: [
      'The matter that caused your payments to be suspended has been resolved and your award has been reinstated.',
    ],
    details: [
      t('Award reference', 'reference'),
      t('Reinstated from', 'reinstatementFrom'),
      t('Amount held during suspension', 'withheldAmount'),
      t('When arrears will be paid', 'arrearsSchedule'),
    ],
    nextSteps: [
      'Your normal payment cycle resumes from the date shown.',
      'Any amount withheld during the suspension will be released as shown above.',
    ],
  },

  // ---------------------------------------------------------------- PAYMENT
  {
    eventCode: 'BENEFITS.PAYMENT.SCHEDULE.CREATED',
    templateFamily: 'BENEFITS_PAYMENT_SCHEDULE_CREATED',
    recipientRole: 'payee',
    name: 'Payment schedule created',
    description: 'Tells the payee when and how they will be paid.',
    communicationClass: 'transactional',
    priority: 'normal',
    subject: 'Your payment schedule for award {{payload.reference}}',
    preheader: 'Here is when and how you will be paid.',
    headline: 'Your payment schedule',
    intro: [
      'A payment schedule has been created for your award. It sets out how much you will receive, how often, and by what method.',
    ],
    details: [
      t('Award reference', 'reference'),
      t('Amount per payment', 'paymentAmount'),
      t('Frequency', 'paymentFrequency'),
      t('First payment date', 'firstPaymentDate'),
      t('Payment method', 'paymentMethod'),
    ],
    nextSteps: [
      'Check that the payment method and account details are correct.',
      'Tell us at once if your bank details change.',
    ],
  },
  {
    eventCode: 'BENEFITS.PAYMENT.ISSUED',
    templateFamily: 'BENEFITS_PAYMENT_ISSUED',
    recipientRole: 'payee',
    name: 'Benefit payment issued',
    description: 'Confirms that a benefit payment has been released to the payee.',
    communicationClass: 'transactional',
    priority: 'normal',
    subject: 'Payment of {{payload.paymentAmount}} has been issued',
    preheader: 'A benefit payment has been released to you.',
    headline: 'A payment has been issued to you',
    intro: [
      'A payment has been released against your benefit award. The details are below.',
    ],
    details: [
      t('Award reference', 'reference'),
      t('Amount', 'paymentAmount'),
      t('Payment date', 'paymentDate'),
      t('Method', 'paymentMethod'),
      t('Period covered', 'paymentPeriod'),
      t('Payment reference', 'paymentReference'),
    ],
    nextSteps: [
      'Allow the normal clearing time for your payment method.',
      'Contact us if the payment has not reached you within that time.',
    ],
  },
  {
    eventCode: 'BENEFITS.PAYMENT.CANCELLED',
    templateFamily: 'BENEFITS_PAYMENT_CANCELLED',
    recipientRole: 'payee',
    name: 'Benefit payment cancelled',
    description: 'Notifies the payee that a scheduled or issued payment was cancelled.',
    communicationClass: 'transactional',
    priority: 'high',
    subject: 'A payment on award {{payload.reference}} has been cancelled',
    preheader: 'A payment has been cancelled before reaching you.',
    headline: 'A payment has been cancelled',
    intro: [
      'A payment on your award has been cancelled. This means the amount shown will not reach you as originally planned.',
    ],
    details: [
      t('Award reference', 'reference'),
      t('Amount', 'paymentAmount'),
      t('Original payment date', 'paymentDate'),
      t('Reason for cancellation', 'cancellationReason'),
    ],
    nextSteps: [
      'If the cancellation was caused by incorrect payment details, send us the corrected details.',
      'Where the amount is still due, a replacement payment will be arranged.',
    ],
  },
  {
    eventCode: 'BENEFITS.PAYMENT.REISSUED',
    templateFamily: 'BENEFITS_PAYMENT_REISSUED',
    recipientRole: 'payee',
    name: 'Benefit payment reissued',
    description: 'Confirms that a replacement payment has been issued.',
    communicationClass: 'transactional',
    priority: 'high',
    subject: 'A replacement payment has been issued for award {{payload.reference}}',
    preheader: 'Your replacement payment is on its way.',
    headline: 'A replacement payment has been issued',
    intro: [
      'A replacement payment has been issued to you following the earlier payment that did not complete.',
    ],
    details: [
      t('Award reference', 'reference'),
      t('Amount', 'paymentAmount'),
      t('Reissued on', 'paymentDate'),
      t('Method', 'paymentMethod'),
      t('Reason for reissue', 'reissueReason'),
    ],
    nextSteps: [
      'Allow the normal clearing time for the replacement payment.',
      'Tell us if it does not arrive within that time.',
    ],
  },
  {
    eventCode: 'BENEFITS.PAYMENT.CORRECTION.COMPLETED',
    templateFamily: 'BENEFITS_PAYMENT_CORRECTION_COMPLETED',
    recipientRole: 'payee',
    name: 'Payment correction completed',
    description: 'Explains a correction applied to a payment record.',
    communicationClass: 'transactional',
    priority: 'normal',
    subject: 'A payment correction was applied to award {{payload.reference}}',
    preheader: 'We corrected a payment on your record.',
    headline: 'A payment correction has been applied',
    intro: [
      'A correction has been completed on a payment linked to your award. The details of the correction are below.',
    ],
    details: [
      t('Award reference', 'reference'),
      t('What changed', 'correctionSummary'),
      t('Corrected amount', 'paymentAmount'),
      t('Corrected on', 'correctedOn'),
    ],
    nextSteps: [
      'Check the corrected amount against your bank record.',
      'Contact us if the corrected figure still looks wrong.',
    ],
  },

  // ------------------------------------------------------- LIFE CERTIFICATE
  {
    eventCode: 'BENEFITS.LIFE_CERTIFICATE.OBLIGATION.CREATED',
    templateFamily: 'BENEFITS_LC_OBLIGATION_CREATED',
    recipientRole: 'beneficiary',
    name: 'Life certificate obligation created',
    description:
      'Tells a pensioner that a life certificate is now required for the coming cycle.',
    communicationClass: 'legal_mandatory',
    priority: 'normal',
    subject: 'A life certificate is required for award {{payload.reference}}',
    preheader: 'You will need to complete a life certificate for this cycle.',
    headline: 'A life certificate is now required',
    intro: [
      'To keep your pension in payment, the Board must confirm periodically that you continue to be eligible. A life certificate has been raised on your record for the cycle shown below.',
    ],
    details: [
      t('Award reference', 'reference'),
      t('Certification cycle', 'certificationCycle'),
      t('Due date', 'dueDate'),
      t('How to certify', 'submissionChannel'),
    ],
    nextSteps: [
      'Have the certificate completed and witnessed as instructed.',
      'Return it to us before the due date.',
      'We will confirm in writing once it is verified.',
    ],
    notice:
      'If the certificate is not received by the due date, your payments may be suspended until it is provided.',
  },
  {
    eventCode: 'BENEFITS.LIFE_CERTIFICATE.DUE',
    templateFamily: 'BENEFITS_LC_DUE',
    recipientRole: 'beneficiary',
    name: 'Life certificate due',
    description: 'Notifies the pensioner that the life certificate is now due.',
    communicationClass: 'legal_mandatory',
    priority: 'high',
    subject: 'Your life certificate is due by {{payload.dueDate}}',
    preheader: 'Please complete and return your life certificate.',
    headline: 'Your life certificate is due',
    intro: [
      'Your life certificate for the current cycle is now due. Please complete and return it so that your pension continues without interruption.',
    ],
    details: [
      t('Award reference', 'reference'),
      t('Certification cycle', 'certificationCycle'),
      t('Due date', 'dueDate'),
      t('How to certify', 'submissionChannel'),
    ],
    nextSteps: [
      'Complete the certificate and have it witnessed as instructed.',
      'Return it before the due date.',
    ],
    notice: 'Payments may be suspended if the certificate is not received on time.',
  },
  {
    eventCode: 'BENEFITS.LIFE_CERTIFICATE.REMINDER.DUE',
    templateFamily: 'BENEFITS_LC_REMINDER',
    recipientRole: 'beneficiary',
    name: 'Life certificate reminder',
    description: 'Reminds the pensioner that a life certificate is still outstanding.',
    communicationClass: 'legal_mandatory',
    priority: 'high',
    subject: 'Reminder: your life certificate is still outstanding',
    preheader: 'We have not yet received your life certificate.',
    headline: 'Reminder — your life certificate is still outstanding',
    intro: [
      'Our records show that we have not yet received your life certificate for the current cycle.',
    ],
    details: [
      t('Award reference', 'reference'),
      t('Certification cycle', 'certificationCycle'),
      t('Due date', 'dueDate'),
      t('Days remaining', 'daysRemaining'),
    ],
    nextSteps: [
      'Return the completed certificate as soon as possible.',
      'Ignore this reminder if you have posted it in the last few days.',
    ],
    notice:
      'If we still do not receive it, your pension may be suspended until the certificate is provided.',
  },
  {
    eventCode: 'BENEFITS.LIFE_CERTIFICATE.GRACE.STARTED',
    templateFamily: 'BENEFITS_LC_GRACE_STARTED',
    recipientRole: 'beneficiary',
    name: 'Life certificate grace period started',
    description: 'Tells the pensioner that a grace period has begun before suspension.',
    communicationClass: 'legal_mandatory',
    priority: 'urgent',
    subject: 'Final period to return your life certificate',
    preheader: 'A grace period has started before payments are affected.',
    headline: 'A grace period has started for your life certificate',
    intro: [
      'Your life certificate was not received by the due date. A short grace period has now started before your payments are affected.',
    ],
    details: [
      t('Award reference', 'reference'),
      t('Original due date', 'dueDate'),
      t('Grace period ends', 'graceEndsOn'),
      t('How to certify', 'submissionChannel'),
    ],
    nextSteps: [
      'Return the completed certificate before the grace period ends.',
      'Contact us immediately if you are unable to complete it for medical reasons.',
    ],
    notice:
      'If the certificate is not received by {{payload.graceEndsOn}}, payments will be suspended.',
  },
  {
    eventCode: 'BENEFITS.LIFE_CERTIFICATE.OVERDUE',
    templateFamily: 'BENEFITS_LC_OVERDUE',
    recipientRole: 'beneficiary',
    name: 'Life certificate overdue',
    description: 'Notifies the pensioner that the certificate is overdue.',
    communicationClass: 'legal_mandatory',
    priority: 'urgent',
    subject: 'Your life certificate is overdue — action required',
    preheader: 'Your life certificate has not been received.',
    headline: 'Your life certificate is overdue',
    intro: [
      'Your life certificate remains outstanding after the due date and any grace period allowed.',
    ],
    details: [
      t('Award reference', 'reference'),
      t('Due date', 'dueDate'),
      t('Days overdue', 'daysOverdue'),
      t('Consequence if not received', 'consequenceSummary'),
    ],
    nextSteps: [
      'Return the completed certificate immediately.',
      'Contact us if you need help completing it.',
    ],
    notice:
      'Payments may already be held. They will resume once a valid certificate is verified.',
  },
  {
    eventCode: 'BENEFITS.LIFE_CERTIFICATE.RECEIVED',
    templateFamily: 'BENEFITS_LC_RECEIVED',
    recipientRole: 'beneficiary',
    name: 'Life certificate received',
    description: 'Confirms receipt of a life certificate before verification.',
    communicationClass: 'transactional',
    priority: 'normal',
    subject: 'We have received your life certificate',
    preheader: 'Your certificate is with us and is being checked.',
    headline: 'Your life certificate has been received',
    intro: [
      'Thank you. Your life certificate has been received and is now being checked.',
    ],
    details: [
      t('Award reference', 'reference'),
      t('Certification cycle', 'certificationCycle'),
      t('Received on', 'receivedOn'),
    ],
    nextSteps: [
      'An officer will verify the certificate.',
      'We will write to you again once verification is complete.',
    ],
    closing: 'No further action is needed from you at this stage.',
  },
  {
    eventCode: 'BENEFITS.LIFE_CERTIFICATE.VERIFIED',
    templateFamily: 'BENEFITS_LC_VERIFIED',
    recipientRole: 'beneficiary',
    name: 'Life certificate verified',
    description: 'Confirms that the life certificate has been accepted.',
    communicationClass: 'transactional',
    priority: 'normal',
    subject: 'Your life certificate has been accepted',
    preheader: 'Your certification is complete for this cycle.',
    headline: 'Your life certificate has been accepted',
    intro: [
      'Your life certificate has been verified and accepted. Your pension will continue without interruption.',
    ],
    details: [
      t('Award reference', 'reference'),
      t('Certification cycle', 'certificationCycle'),
      t('Verified on', 'verifiedOn'),
      t('Next certification due', 'nextDueDate'),
    ],
    nextSteps: [
      'Keep this notice for your records.',
      'We will contact you again when the next certification falls due.',
    ],
  },
  {
    eventCode: 'BENEFITS.LIFE_CERTIFICATE.REJECTED',
    templateFamily: 'BENEFITS_LC_REJECTED',
    recipientRole: 'beneficiary',
    name: 'Life certificate rejected',
    description: 'Explains why a life certificate could not be accepted.',
    communicationClass: 'legal_mandatory',
    priority: 'urgent',
    subject: 'Your life certificate could not be accepted',
    preheader: 'There is a problem with the certificate you sent.',
    headline: 'Your life certificate could not be accepted',
    intro: [
      'We have checked the life certificate you returned. Unfortunately it cannot be accepted for the reason shown below.',
    ],
    details: [
      t('Award reference', 'reference'),
      t('Certification cycle', 'certificationCycle'),
      t('Reason', 'rejectionReason'),
      t('What to do', 'resolutionRequirement'),
      t('Return by', 'dueDate'),
    ],
    nextSteps: [
      'Correct the issue described above.',
      'Return a fresh certificate before the date shown.',
    ],
    notice: 'Your pension may be suspended if a valid certificate is not received.',
  },
  {
    eventCode: 'BENEFITS.LIFE_CERTIFICATE.RESUBMISSION_REQUIRED',
    templateFamily: 'BENEFITS_LC_RESUBMISSION_REQUIRED',
    recipientRole: 'beneficiary',
    name: 'Life certificate resubmission required',
    description: 'Asks the pensioner to submit the life certificate again.',
    communicationClass: 'legal_mandatory',
    priority: 'urgent',
    subject: 'Please submit your life certificate again',
    preheader: 'A fresh life certificate is required.',
    headline: 'Please submit your life certificate again',
    intro: [
      'A fresh life certificate is required before your certification for this cycle can be completed.',
    ],
    details: [
      t('Award reference', 'reference'),
      t('Certification cycle', 'certificationCycle'),
      t('What must be corrected', 'resolutionRequirement'),
      t('Return by', 'dueDate'),
      t('How to certify', 'submissionChannel'),
    ],
    nextSteps: [
      'Have a new certificate completed and witnessed.',
      'Return it before the date shown.',
    ],
  },
  {
    eventCode: 'BENEFITS.LIFE_CERTIFICATE.WAIVED',
    templateFamily: 'BENEFITS_LC_WAIVED',
    recipientRole: 'beneficiary',
    name: 'Life certificate waived',
    description: 'Confirms that the certification requirement has been waived.',
    communicationClass: 'transactional',
    priority: 'normal',
    subject: 'Your life certificate requirement has been waived',
    preheader: 'You do not need to certify for this cycle.',
    headline: 'Your life certificate requirement has been waived',
    intro: [
      'The requirement to provide a life certificate for this cycle has been waived. You do not need to take any action.',
    ],
    details: [
      t('Award reference', 'reference'),
      t('Certification cycle', 'certificationCycle'),
      t('Reason for waiver', 'waiverReason'),
      t('Next certification due', 'nextDueDate'),
    ],
    nextSteps: [
      'Keep this notice for your records.',
      'We will contact you when the next certification falls due.',
    ],
  },
  {
    eventCode: 'BENEFITS.LIFE_CERTIFICATE.DEFERRED',
    templateFamily: 'BENEFITS_LC_DEFERRED',
    recipientRole: 'beneficiary',
    name: 'Life certificate deferred',
    description: 'Confirms a new deferred deadline for certification.',
    communicationClass: 'transactional',
    priority: 'normal',
    subject: 'Your life certificate deadline has been extended',
    preheader: 'You have more time to return your certificate.',
    headline: 'Your life certificate deadline has been extended',
    intro: [
      'The deadline for returning your life certificate has been extended. Your new deadline is shown below.',
    ],
    details: [
      t('Award reference', 'reference'),
      t('Certification cycle', 'certificationCycle'),
      t('New due date', 'dueDate'),
      t('Reason for deferral', 'deferralReason'),
    ],
    nextSteps: [
      'Return the completed certificate before the new date.',
      'Contact us if you still cannot meet the deadline.',
    ],
  },

  // --------------------------------------------------------- MEDICAL REVIEW
  {
    eventCode: 'BENEFITS.MEDICAL_REVIEW.REFERRAL.ISSUED',
    templateFamily: 'BENEFITS_MR_REFERRAL_ISSUED',
    recipientRole: 'medical_provider',
    name: 'Medical referral issued',
    description: 'Sends a medical referral instruction to the examining provider.',
    communicationClass: 'transactional',
    priority: 'high',
    subject: 'Medical referral {{payload.reference}} for assessment',
    preheader: 'A referral has been issued for medical assessment.',
    headline: 'Medical referral issued',
    intro: [
      'A referral has been issued to you for a medical assessment in connection with a benefit case. The details required to carry out the assessment are shown below.',
    ],
    details: [
      t('Referral reference', 'reference'),
      t('Case reference', 'caseReference'),
      t('Assessment required', 'assessmentType'),
      t('Question to be answered', 'referralQuestion'),
      t('Report due by', 'dueDate'),
    ],
    nextSteps: [
      'Arrange the assessment with the person concerned.',
      'Return your report by the due date, addressing the referral question.',
      'Contact the Board if you need further information before reporting.',
    ],
    notice:
      'Please treat all case information as confidential and disclose it only for the purpose of this assessment.',
  },
  {
    eventCode: 'BENEFITS.MEDICAL_REVIEW.APPOINTMENT.SCHEDULED',
    templateFamily: 'BENEFITS_MR_APPOINTMENT_SCHEDULED',
    recipientRole: 'claimant',
    name: 'Medical appointment scheduled',
    description: 'Tells the claimant when and where their medical appointment is.',
    communicationClass: 'transactional',
    priority: 'high',
    subject: 'Your medical appointment on {{payload.appointmentDate}}',
    preheader: 'An appointment has been arranged for your medical assessment.',
    headline: 'Your medical appointment has been arranged',
    intro: [
      'An appointment has been arranged for a medical assessment in connection with your benefit case. Please attend at the time and place shown below.',
    ],
    details: [
      t('Case reference', 'reference'),
      t('Date', 'appointmentDate'),
      t('Time', 'appointmentTime'),
      t('Location', 'appointmentLocation'),
      t('Examiner', 'examinerName'),
      t('What to bring', 'bringItems'),
    ],
    nextSteps: [
      'Arrive a few minutes early and bring valid identification.',
      'Bring any medical reports or medication list you have.',
      'Contact us as soon as possible if you cannot attend.',
    ],
    notice:
      'Failure to attend without good reason may affect your benefit entitlement.',
  },
  {
    eventCode: 'BENEFITS.MEDICAL_REVIEW.APPOINTMENT.RESCHEDULED',
    templateFamily: 'BENEFITS_MR_APPOINTMENT_RESCHEDULED',
    recipientRole: 'claimant',
    name: 'Medical appointment rescheduled',
    description: 'Notifies the claimant that the appointment has moved.',
    communicationClass: 'transactional',
    priority: 'high',
    subject: 'Your medical appointment has been moved to {{payload.appointmentDate}}',
    preheader: 'Your appointment date or place has changed.',
    headline: 'Your medical appointment has been rescheduled',
    intro: [
      'Your medical appointment has been rescheduled. Please note the new details below and disregard the previous appointment.',
    ],
    details: [
      t('Case reference', 'reference'),
      t('New date', 'appointmentDate'),
      t('New time', 'appointmentTime'),
      t('Location', 'appointmentLocation'),
      t('Reason for the change', 'rescheduleReason'),
    ],
    nextSteps: [
      'Make a note of the new appointment.',
      'Tell us immediately if the new time is not possible for you.',
    ],
  },
  {
    eventCode: 'BENEFITS.MEDICAL_REVIEW.APPOINTMENT.CANCELLED',
    templateFamily: 'BENEFITS_MR_APPOINTMENT_CANCELLED',
    recipientRole: 'claimant',
    name: 'Medical appointment cancelled',
    description: 'Notifies the claimant that the appointment has been cancelled.',
    communicationClass: 'transactional',
    priority: 'high',
    subject: 'Your medical appointment has been cancelled',
    preheader: 'Do not attend the appointment previously arranged.',
    headline: 'Your medical appointment has been cancelled',
    intro: [
      'The medical appointment previously arranged for you has been cancelled. Please do not attend.',
    ],
    details: [
      t('Case reference', 'reference'),
      t('Cancelled appointment', 'appointmentDate'),
      t('Reason', 'cancellationReason'),
      t('What happens now', 'nextActionSummary'),
    ],
    nextSteps: [
      'Wait for us to contact you with a new appointment, if one is needed.',
      'Contact us if you have not heard from us within two weeks.',
    ],
  },
  {
    eventCode: 'BENEFITS.MEDICAL_REVIEW.APPOINTMENT.NON_ATTENDANCE',
    templateFamily: 'BENEFITS_MR_NON_ATTENDANCE',
    recipientRole: 'claimant',
    name: 'Medical appointment missed',
    description:
      'Records non-attendance at a medical appointment and explains the consequence.',
    communicationClass: 'legal_mandatory',
    priority: 'urgent',
    subject: 'You did not attend your medical appointment',
    preheader: 'Your appointment was missed — please contact us.',
    headline: 'You did not attend your medical appointment',
    intro: [
      'Our records show that you did not attend the medical appointment arranged for you, and we have not received an explanation.',
    ],
    details: [
      t('Case reference', 'reference'),
      t('Missed appointment', 'appointmentDate'),
      t('Location', 'appointmentLocation'),
      t('Respond by', 'dueDate'),
    ],
    nextSteps: [
      'Contact us and explain why you could not attend.',
      'A further appointment may be arranged if you have good reason.',
    ],
    notice:
      'If we do not hear from you by {{payload.dueDate}}, a decision may be made on the information already held, which can affect your entitlement.',
  },
  {
    eventCode: 'BENEFITS.MEDICAL_REVIEW.SECOND_OPINION.REQUESTED',
    templateFamily: 'BENEFITS_MR_SECOND_OPINION_REQUESTED',
    recipientRole: 'medical_provider',
    name: 'Second medical opinion requested',
    description: 'Requests an independent second medical opinion on a case.',
    communicationClass: 'transactional',
    priority: 'high',
    subject: 'Request for a second medical opinion — {{payload.reference}}',
    preheader: 'An independent second opinion has been requested.',
    headline: 'Request for a second medical opinion',
    intro: [
      'The Board requests an independent second medical opinion in connection with the case below.',
    ],
    details: [
      t('Referral reference', 'reference'),
      t('Case reference', 'caseReference'),
      t('Question to be answered', 'referralQuestion'),
      t('Material provided', 'materialProvided'),
      t('Opinion due by', 'dueDate'),
    ],
    nextSteps: [
      'Review the material provided.',
      'Return your written opinion by the due date.',
    ],
    notice: 'Please treat all case material as confidential.',
  },
  {
    eventCode: 'BENEFITS.MEDICAL_REVIEW.CLARIFICATION.REQUESTED',
    templateFamily: 'BENEFITS_MR_CLARIFICATION_REQUESTED',
    recipientRole: 'medical_provider',
    name: 'Medical clarification requested',
    description: 'Asks the reporting provider to clarify part of a medical report.',
    communicationClass: 'transactional',
    priority: 'high',
    subject: 'Clarification needed on medical report {{payload.reference}}',
    preheader: 'We need clarification on part of your report.',
    headline: 'Clarification requested on a medical report',
    intro: [
      'Thank you for your report. Before the case can proceed, we need clarification on the point set out below.',
    ],
    details: [
      t('Referral reference', 'reference'),
      t('Case reference', 'caseReference'),
      t('Point requiring clarification', 'clarificationRequest'),
      t('Respond by', 'dueDate'),
    ],
    nextSteps: [
      'Provide a short written clarification addressing the point raised.',
      'Return it by the date shown.',
    ],
  },
  {
    eventCode: 'BENEFITS.MEDICAL_REVIEW.BOARD.SESSION.SCHEDULED',
    templateFamily: 'BENEFITS_MR_BOARD_SESSION_SCHEDULED',
    recipientRole: 'board_member',
    name: 'Medical board session scheduled',
    description: 'Convenes members for a scheduled medical board session.',
    communicationClass: 'operational',
    priority: 'high',
    subject: 'Medical board session on {{payload.sessionDate}}',
    preheader: 'A medical board session has been scheduled.',
    headline: 'Medical board session scheduled',
    intro: [
      'A medical board session has been scheduled. Your attendance is requested.',
    ],
    details: [
      t('Session reference', 'reference'),
      t('Date', 'sessionDate'),
      t('Time', 'sessionTime'),
      t('Location', 'sessionLocation'),
      t('Cases listed', 'caseCount'),
    ],
    nextSteps: [
      'Review the case papers before the session.',
      'Confirm your attendance with the secretariat.',
    ],
    notice: 'All case papers are confidential and must not be shared outside the board.',
  },
  {
    eventCode: 'BENEFITS.MEDICAL_REVIEW.BOARD.EVIDENCE.REQUESTED',
    templateFamily: 'BENEFITS_MR_BOARD_EVIDENCE_REQUESTED',
    recipientRole: 'claimant',
    name: 'Medical board evidence requested',
    description: 'Requests further medical evidence ahead of a board review.',
    communicationClass: 'transactional',
    priority: 'high',
    subject: 'Medical evidence needed for your case {{payload.reference}}',
    preheader: 'The medical board needs further evidence from you.',
    headline: 'Further medical evidence is needed',
    intro: [
      'The medical board reviewing your case requires further evidence before it can reach a conclusion.',
    ],
    details: [
      t('Case reference', 'reference'),
      t('Evidence required', 'evidenceRequested'),
      t('Send by', 'dueDate'),
      t('How to send', 'submissionChannel'),
    ],
    nextSteps: [
      'Obtain the evidence listed above from your treating practitioner.',
      'Send it to us before the due date.',
    ],
    notice:
      'If the evidence is not received in time, the board may proceed on the information already held.',
  },

  // ----------------------------------------------------------------- APPEAL
  {
    eventCode: 'BENEFITS.APPEAL.SUBMITTED',
    templateFamily: 'BENEFITS_APPEAL_SUBMITTED',
    recipientRole: 'appellant',
    name: 'Appeal submitted',
    description: 'Confirms that an appeal has been lodged.',
    communicationClass: 'legal_mandatory',
    priority: 'high',
    subject: 'Your appeal {{payload.reference}} has been lodged',
    preheader: 'We have received your appeal.',
    headline: 'Your appeal has been lodged',
    intro: [
      'We confirm that your appeal has been lodged and recorded. This message is your proof of lodgement.',
    ],
    details: [
      t('Appeal reference', 'reference'),
      t('Decision appealed', 'decisionUnderAppeal'),
      t('Grounds recorded', 'appealGrounds'),
      t('Lodged on', 'submittedOn'),
    ],
    nextSteps: [
      'Your appeal will be checked for admissibility.',
      'We will write to you with the outcome of that check.',
    ],
  },
  {
    eventCode: 'BENEFITS.APPEAL.ACKNOWLEDGED',
    templateFamily: 'BENEFITS_APPEAL_ACKNOWLEDGED',
    recipientRole: 'appellant',
    name: 'Appeal acknowledged',
    description: 'Formally acknowledges an appeal and sets expectations.',
    communicationClass: 'legal_mandatory',
    priority: 'normal',
    subject: 'Acknowledgement of your appeal {{payload.reference}}',
    preheader: 'Your appeal has been acknowledged.',
    headline: 'Your appeal has been acknowledged',
    intro: [
      'Your appeal has been formally acknowledged and assigned for handling.',
    ],
    details: [
      t('Appeal reference', 'reference'),
      t('Acknowledged on', 'acknowledgedOn'),
      t('Handling stage', 'appealStage'),
      t('Expected next milestone', 'nextMilestone'),
    ],
    nextSteps: [
      'No action is needed from you at this stage.',
      'We will contact you if further information or a hearing is required.',
    ],
  },
  {
    eventCode: 'BENEFITS.APPEAL.ADMISSIBLE',
    templateFamily: 'BENEFITS_APPEAL_ADMISSIBLE',
    recipientRole: 'appellant',
    name: 'Appeal admissible',
    description: 'Tells the appellant the appeal has been accepted for consideration.',
    communicationClass: 'legal_mandatory',
    priority: 'high',
    subject: 'Your appeal {{payload.reference}} will be considered',
    preheader: 'Your appeal has been accepted as admissible.',
    headline: 'Your appeal has been accepted',
    intro: [
      'Your appeal has been examined and found admissible. It will now proceed to consideration on its merits.',
    ],
    details: [
      t('Appeal reference', 'reference'),
      t('Decision appealed', 'decisionUnderAppeal'),
      t('Admissible from', 'admissibilityDate'),
      t('Next stage', 'nextMilestone'),
    ],
    nextSteps: [
      'Send any further supporting evidence as soon as possible.',
      'We will notify you if a hearing is arranged.',
    ],
  },
  {
    eventCode: 'BENEFITS.APPEAL.INADMISSIBLE',
    templateFamily: 'BENEFITS_APPEAL_INADMISSIBLE',
    recipientRole: 'appellant',
    name: 'Appeal inadmissible',
    description:
      'Tells the appellant the appeal cannot be considered and explains why.',
    communicationClass: 'legal_mandatory',
    priority: 'high',
    subject: 'Your appeal {{payload.reference}} cannot be considered',
    preheader: 'Your appeal has been found inadmissible.',
    headline: 'Your appeal cannot be considered',
    intro: [
      'Your appeal has been examined. It cannot be considered for the reason set out below.',
    ],
    details: [
      t('Appeal reference', 'reference'),
      t('Decision appealed', 'decisionUnderAppeal'),
      t('Reason', 'inadmissibilityReason'),
      t('Determined on', 'decisionDate'),
    ],
    nextSteps: [
      'Read the reason given above.',
      'If the reason can be cured — for example a missing document — you may write to us again.',
    ],
    notice:
      'This decision concerns admissibility only. It is not a decision on the merits of your case.',
  },
  {
    eventCode: 'BENEFITS.APPEAL.HEARING.SCHEDULED',
    templateFamily: 'BENEFITS_APPEAL_HEARING_SCHEDULED',
    recipientRole: 'appellant',
    name: 'Appeal hearing scheduled',
    description: 'Notifies the appellant of the hearing date, time and place.',
    communicationClass: 'legal_mandatory',
    priority: 'urgent',
    subject: 'Your appeal hearing is on {{payload.hearingDate}}',
    preheader: 'A hearing has been scheduled for your appeal.',
    headline: 'Your appeal hearing has been scheduled',
    intro: [
      'A hearing has been scheduled for your appeal. Please make arrangements to attend.',
    ],
    details: [
      t('Appeal reference', 'reference'),
      t('Hearing date', 'hearingDate'),
      t('Hearing time', 'hearingTime'),
      t('Venue', 'hearingVenue'),
      t('Hearing type', 'hearingType'),
    ],
    nextSteps: [
      'Confirm your attendance with the appeals secretariat.',
      'Bring any documents you intend to rely on.',
      'Tell us in advance if you will be represented.',
    ],
    notice:
      'If you do not attend, the hearing may proceed in your absence and a decision may be made on the papers.',
  },
  {
    eventCode: 'BENEFITS.APPEAL.DECIDED',
    templateFamily: 'BENEFITS_APPEAL_DECIDED',
    recipientRole: 'appellant',
    name: 'Appeal decided',
    description: 'Issues the appeal decision and any further rights.',
    communicationClass: 'legal_mandatory',
    priority: 'urgent',
    subject: 'Decision on your appeal {{payload.reference}}',
    preheader: 'A decision has been made on your appeal.',
    headline: 'Decision on your appeal',
    intro: [
      'Your appeal has been decided. The outcome and the reasons for it are set out below.',
    ],
    details: [
      t('Appeal reference', 'reference'),
      t('Outcome', 'appealOutcome'),
      t('Reasons', 'decisionReason'),
      t('Decision date', 'decisionDate'),
      t('Effect on your benefit', 'implementationSummary'),
    ],
    nextSteps: [
      'Read the outcome and reasons carefully.',
      'Where the decision changes your benefit, the change will be implemented and confirmed to you separately.',
    ],
    notice:
      'If you disagree with this decision, any further right of review must be exercised within the period allowed by law.',
  },
  {
    eventCode: 'BENEFITS.APPEAL.WITHDRAWN',
    templateFamily: 'BENEFITS_APPEAL_WITHDRAWN',
    recipientRole: 'appellant',
    name: 'Appeal withdrawn',
    description: 'Confirms withdrawal of an appeal and its consequences.',
    communicationClass: 'legal_mandatory',
    priority: 'normal',
    subject: 'Your appeal {{payload.reference}} has been withdrawn',
    preheader: 'We have closed your appeal at your request.',
    headline: 'Your appeal has been withdrawn',
    intro: [
      'We have recorded the withdrawal of your appeal. No hearing will take place and no appeal decision will be issued.',
    ],
    details: [
      t('Appeal reference', 'reference'),
      t('Withdrawn on', 'withdrawnOn'),
      t('Reason recorded', 'withdrawalReason'),
      t('Decision that stands', 'decisionUnderAppeal'),
    ],
    nextSteps: [
      'The original decision remains in force.',
      'Contact us if the withdrawal was recorded in error.',
    ],
  },

  // ------------------------------------------------------------ OVERPAYMENT
  {
    eventCode: 'BENEFITS.OVERPAYMENT.NOTICE.ISSUED',
    templateFamily: 'BENEFITS_OVP_NOTICE_ISSUED',
    recipientRole: 'debtor',
    name: 'Overpayment notice issued',
    description:
      'Issues a formal notice that an overpayment has been identified, with the right to make representations.',
    communicationClass: 'legal_mandatory',
    priority: 'urgent',
    subject: 'Notice of overpayment {{payload.reference}}',
    preheader: 'An overpayment has been identified on your record.',
    headline: 'Notice of overpayment',
    intro: [
      'A review of your benefit record shows that you were paid more than you were entitled to receive. This notice sets out the amount, the period and the reason.',
    ],
    details: [
      t('Overpayment reference', 'reference'),
      t('Amount overpaid', 'overpaidAmount'),
      t('Period covered', 'overpaymentPeriod'),
      t('Cause', 'overpaymentCause'),
      t('Respond by', 'dueDate'),
    ],
    nextSteps: [
      'Read the figures above and check them against your records.',
      'If you disagree, send us your written representations before the date shown.',
      'If you accept the amount, contact us to agree how it will be repaid.',
    ],
    notice:
      'You have the right to make representations before recovery begins. If we do not hear from you by {{payload.dueDate}}, recovery action may start.',
  },
  {
    eventCode: 'BENEFITS.OVERPAYMENT.REPRESENTATION.RECEIVED',
    templateFamily: 'BENEFITS_OVP_REPRESENTATION_RECEIVED',
    recipientRole: 'debtor',
    name: 'Overpayment representation received',
    description: 'Confirms receipt of representations against an overpayment.',
    communicationClass: 'transactional',
    priority: 'normal',
    subject: 'We have received your response on overpayment {{payload.reference}}',
    preheader: 'Your representations are being considered.',
    headline: 'We have received your representations',
    intro: [
      'Thank you. Your representations about the overpayment have been received and will be considered before any decision on recovery is made.',
    ],
    details: [
      t('Overpayment reference', 'reference'),
      t('Received on', 'receivedOn'),
      t('Points raised', 'representationSummary'),
    ],
    nextSteps: [
      'An officer will consider what you have told us.',
      'We will write to you with the outcome.',
    ],
    notice: 'Recovery is normally held while your representations are considered.',
  },
  {
    eventCode: 'BENEFITS.OVERPAYMENT.LIABILITY.CONFIRMED',
    templateFamily: 'BENEFITS_OVP_LIABILITY_CONFIRMED',
    recipientRole: 'debtor',
    name: 'Overpayment liability confirmed',
    description: 'Confirms the final recoverable amount after consideration.',
    communicationClass: 'legal_mandatory',
    priority: 'urgent',
    subject: 'Confirmed amount recoverable — overpayment {{payload.reference}}',
    preheader: 'The recoverable amount has been confirmed.',
    headline: 'The overpayment amount has been confirmed',
    intro: [
      'We have considered all the information available, including anything you sent us. The recoverable amount has now been confirmed.',
    ],
    details: [
      t('Overpayment reference', 'reference'),
      t('Amount recoverable', 'overpaidAmount'),
      t('Period covered', 'overpaymentPeriod'),
      t('Reason liability stands', 'decisionReason'),
      t('Respond by', 'dueDate'),
    ],
    nextSteps: [
      'Contact us to agree a repayment arrangement.',
      'If you cannot repay in full, ask about an instalment plan or a waiver.',
    ],
    notice:
      'If no arrangement is agreed, recovery may be made from ongoing benefit payments or by other lawful means. You may appeal this determination.',
  },
  {
    eventCode: 'BENEFITS.OVERPAYMENT.RECOVERY_PLAN.PROPOSED',
    templateFamily: 'BENEFITS_OVP_RECOVERY_PLAN_PROPOSED',
    recipientRole: 'debtor',
    name: 'Recovery plan proposed',
    description: 'Puts a proposed repayment plan to the debtor for agreement.',
    communicationClass: 'transactional',
    priority: 'high',
    subject: 'Proposed repayment plan for overpayment {{payload.reference}}',
    preheader: 'Please review the proposed repayment terms.',
    headline: 'A repayment plan has been proposed',
    intro: [
      'We have prepared a proposed repayment plan for the confirmed overpayment. Please review the terms below.',
    ],
    details: [
      t('Overpayment reference', 'reference'),
      t('Total to repay', 'overpaidAmount'),
      t('Instalment amount', 'instalmentAmount'),
      t('Frequency', 'instalmentFrequency'),
      t('First instalment due', 'firstInstalmentDate'),
      t('Respond by', 'dueDate'),
    ],
    nextSteps: [
      'Tell us whether you accept the proposed terms.',
      'If the instalments are unaffordable, tell us what you can pay and why.',
    ],
  },
  {
    eventCode: 'BENEFITS.OVERPAYMENT.RECOVERY_PLAN.APPROVED',
    templateFamily: 'BENEFITS_OVP_RECOVERY_PLAN_APPROVED',
    recipientRole: 'debtor',
    name: 'Recovery plan approved',
    description: 'Confirms an agreed repayment plan and its terms.',
    communicationClass: 'transactional',
    priority: 'high',
    subject: 'Your repayment plan for overpayment {{payload.reference}} is approved',
    preheader: 'Your repayment plan has been approved.',
    headline: 'Your repayment plan has been approved',
    intro: [
      'Your repayment plan has been approved. Please keep to the terms below so that no further recovery action is needed.',
    ],
    details: [
      t('Overpayment reference', 'reference'),
      t('Total to repay', 'overpaidAmount'),
      t('Instalment amount', 'instalmentAmount'),
      t('Frequency', 'instalmentFrequency'),
      t('First instalment due', 'firstInstalmentDate'),
      t('How to pay', 'paymentMethod'),
    ],
    nextSteps: [
      'Make each instalment on or before its due date.',
      'Contact us immediately if your circumstances change and you cannot pay.',
    ],
    notice:
      'If instalments are missed, the full outstanding balance may become due at once.',
  },
  {
    eventCode: 'BENEFITS.OVERPAYMENT.RECOVERY_PLAN.REJECTED',
    templateFamily: 'BENEFITS_OVP_RECOVERY_PLAN_REJECTED',
    recipientRole: 'debtor',
    name: 'Recovery plan rejected',
    description: 'Explains why a proposed repayment plan was not accepted.',
    communicationClass: 'transactional',
    priority: 'high',
    subject: 'Your proposed repayment plan was not accepted',
    preheader: 'We could not accept the plan you proposed.',
    headline: 'Your proposed repayment plan was not accepted',
    intro: [
      'We have considered the repayment plan you proposed for the overpayment. Unfortunately it cannot be accepted for the reason below.',
    ],
    details: [
      t('Overpayment reference', 'reference'),
      t('Amount outstanding', 'overpaidAmount'),
      t('Reason', 'decisionReason'),
      t('Respond by', 'dueDate'),
    ],
    nextSteps: [
      'Contact us to discuss an affordable alternative.',
      'Send evidence of your income and expenses if affordability is the issue.',
    ],
  },
  {
    eventCode: 'BENEFITS.OVERPAYMENT.RECOVERY_PLAN.REVISED',
    templateFamily: 'BENEFITS_OVP_RECOVERY_PLAN_REVISED',
    recipientRole: 'debtor',
    name: 'Recovery plan revised',
    description: 'Confirms revised repayment terms.',
    communicationClass: 'transactional',
    priority: 'normal',
    subject: 'Your repayment plan has been revised',
    preheader: 'The terms of your repayment plan have changed.',
    headline: 'Your repayment plan has been revised',
    intro: [
      'Your repayment plan has been revised. The new terms replace the previous arrangement and take effect immediately.',
    ],
    details: [
      t('Overpayment reference', 'reference'),
      t('Balance outstanding', 'balanceOutstanding'),
      t('New instalment amount', 'instalmentAmount'),
      t('Frequency', 'instalmentFrequency'),
      t('Next instalment due', 'firstInstalmentDate'),
      t('Reason for revision', 'revisionReason'),
    ],
    nextSteps: [
      'Pay each revised instalment on time.',
      'Contact us if the revised terms are still unaffordable.',
    ],
  },
  {
    eventCode: 'BENEFITS.OVERPAYMENT.WAIVER.APPROVED',
    templateFamily: 'BENEFITS_OVP_WAIVER_APPROVED',
    recipientRole: 'debtor',
    name: 'Overpayment waiver approved',
    description: 'Confirms that recovery has been waived in whole or in part.',
    communicationClass: 'legal_mandatory',
    priority: 'high',
    subject: 'Your waiver request on overpayment {{payload.reference}} was approved',
    preheader: 'Recovery has been waived.',
    headline: 'Your waiver request has been approved',
    intro: [
      'Your request for the overpayment to be waived has been approved. The amount waived is shown below.',
    ],
    details: [
      t('Overpayment reference', 'reference'),
      t('Amount waived', 'waivedAmount'),
      t('Balance still recoverable', 'balanceOutstanding'),
      t('Approved on', 'decisionDate'),
      t('Basis for the waiver', 'decisionReason'),
    ],
    nextSteps: [
      'Keep this notice for your records.',
      'If a balance remains, continue to pay it as arranged.',
    ],
  },
  {
    eventCode: 'BENEFITS.OVERPAYMENT.WAIVER.REJECTED',
    templateFamily: 'BENEFITS_OVP_WAIVER_REJECTED',
    recipientRole: 'debtor',
    name: 'Overpayment waiver rejected',
    description: 'Explains why a waiver request was refused.',
    communicationClass: 'legal_mandatory',
    priority: 'high',
    subject: 'Your waiver request on overpayment {{payload.reference}} was refused',
    preheader: 'Your waiver request has not been granted.',
    headline: 'Your waiver request has not been granted',
    intro: [
      'We have considered your request for the overpayment to be waived. The request has been refused for the reason below.',
    ],
    details: [
      t('Overpayment reference', 'reference'),
      t('Amount recoverable', 'overpaidAmount'),
      t('Reason for refusal', 'decisionReason'),
      t('Decided on', 'decisionDate'),
    ],
    nextSteps: [
      'Contact us to agree how the amount will be repaid.',
      'Tell us if your financial circumstances have changed since you applied.',
    ],
    notice: 'You may appeal this determination within the statutory period.',
  },
  {
    eventCode: 'BENEFITS.OVERPAYMENT.RECOVERED',
    templateFamily: 'BENEFITS_OVP_RECOVERED',
    recipientRole: 'debtor',
    name: 'Overpayment fully recovered',
    description: 'Confirms that an overpayment has been repaid in full.',
    communicationClass: 'transactional',
    priority: 'normal',
    subject: 'Overpayment {{payload.reference}} has been repaid in full',
    preheader: 'Your overpayment balance is now clear.',
    headline: 'Your overpayment has been repaid in full',
    intro: [
      'We confirm that the overpayment on your record has been recovered in full. Nothing further is owed on this case.',
    ],
    details: [
      t('Overpayment reference', 'reference'),
      t('Total recovered', 'recoveredAmount'),
      t('Final payment date', 'finalPaymentDate'),
      t('Closing balance', 'balanceOutstanding'),
    ],
    nextSteps: [
      'Keep this notice as proof that the debt is cleared.',
      'Any recovery from your benefit payments will now stop.',
    ],
  },

  // ------------------------------------------------------------- MEANS TEST
  {
    eventCode: 'BENEFITS.MEANS_TEST.SUBMITTED',
    templateFamily: 'BENEFITS_MEANS_TEST_SUBMITTED',
    recipientRole: 'claimant',
    name: 'Means test submitted',
    description: 'Acknowledges a means test declaration.',
    communicationClass: 'transactional',
    priority: 'normal',
    subject: 'We have received your means test declaration {{payload.reference}}',
    preheader: 'Your means test declaration has been received.',
    headline: 'Your means test declaration has been received',
    intro: [
      'Thank you for submitting your means test declaration. It has been recorded and will now be assessed.',
    ],
    details: [
      t('Assessment reference', 'reference'),
      t('Submitted on', 'submittedOn'),
      t('Household size declared', 'householdSize'),
      t('Assessment period', 'assessmentPeriod'),
    ],
    nextSteps: [
      'An officer will assess the declaration and any supporting documents.',
      'We will contact you if further information is needed.',
    ],
    notice:
      'You must tell us if any declared income, asset or household detail changes during the assessment.',
  },
  {
    eventCode: 'BENEFITS.MEANS_TEST.INFORMATION.REQUESTED',
    templateFamily: 'BENEFITS_MEANS_TEST_INFORMATION_REQUESTED',
    recipientRole: 'claimant',
    name: 'Means test information requested',
    description: 'Requests further financial information for a means assessment.',
    communicationClass: 'transactional',
    priority: 'high',
    subject: 'More information needed for your means assessment',
    preheader: 'We need further financial information from you.',
    headline: 'We need more information for your means assessment',
    intro: [
      'Your means assessment cannot be completed until we receive the information listed below.',
    ],
    details: [
      t('Assessment reference', 'reference'),
      t('Information required', 'informationRequested'),
      t('Send by', 'dueDate'),
      t('How to send', 'submissionChannel'),
    ],
    nextSteps: [
      'Gather the items listed above.',
      'Send them before the due date.',
    ],
    notice:
      'If the information is not received, the assessment may be completed on the information already held or refused.',
  },
  {
    eventCode: 'BENEFITS.MEANS_TEST.APPROVED',
    templateFamily: 'BENEFITS_MEANS_TEST_APPROVED',
    recipientRole: 'claimant',
    name: 'Means test approved',
    description: 'Communicates a successful means assessment outcome.',
    communicationClass: 'legal_mandatory',
    priority: 'high',
    subject: 'Outcome of your means assessment {{payload.reference}}',
    preheader: 'Your means assessment has been approved.',
    headline: 'Your means assessment has been approved',
    intro: [
      'Your means assessment has been completed and approved. The assessed figures used in the decision are shown below.',
    ],
    details: [
      t('Assessment reference', 'reference'),
      t('Assessed income', 'assessedIncome'),
      t('Assessed means', 'assessedMeans'),
      t('Effective from', 'effectiveFrom'),
      t('Next reassessment', 'nextReviewDate'),
    ],
    nextSteps: [
      'Check the assessed figures.',
      'Report any change in income, assets or household composition immediately.',
    ],
    notice: 'You may appeal the assessed figures within the statutory period.',
  },
  {
    eventCode: 'BENEFITS.MEANS_TEST.REJECTED',
    templateFamily: 'BENEFITS_MEANS_TEST_REJECTED',
    recipientRole: 'claimant',
    name: 'Means test rejected',
    description: 'Communicates an unsuccessful means assessment outcome.',
    communicationClass: 'legal_mandatory',
    priority: 'high',
    subject: 'Outcome of your means assessment {{payload.reference}}',
    preheader: 'Your means assessment was not approved.',
    headline: 'Outcome of your means assessment',
    intro: [
      'Your means assessment has been completed. On the information assessed, the means condition for this benefit is not met.',
    ],
    details: [
      t('Assessment reference', 'reference'),
      t('Assessed means', 'assessedMeans'),
      t('Applicable threshold', 'meansThreshold'),
      t('Reason', 'decisionReason'),
      t('Decision date', 'decisionDate'),
    ],
    nextSteps: [
      'Check the assessed figures against your own records.',
      'Send us corrected information if anything is wrong.',
    ],
    notice: 'You have the right to appeal this assessment within the statutory period.',
  },
  {
    eventCode: 'BENEFITS.MEANS_TEST.REASSESSMENT.DUE',
    templateFamily: 'BENEFITS_MEANS_TEST_REASSESSMENT_DUE',
    recipientRole: 'claimant',
    name: 'Means reassessment due',
    description: 'Tells the claimant that a periodic means reassessment is due.',
    communicationClass: 'transactional',
    priority: 'high',
    subject: 'Your means reassessment is due by {{payload.dueDate}}',
    preheader: 'A periodic means reassessment is now due.',
    headline: 'Your means reassessment is due',
    intro: [
      'Your benefit is subject to periodic means reassessment. A new declaration is now due so that your entitlement can continue.',
    ],
    details: [
      t('Assessment reference', 'reference'),
      t('Reassessment period', 'assessmentPeriod'),
      t('Due date', 'dueDate'),
      t('What to provide', 'informationRequested'),
    ],
    nextSteps: [
      'Complete a new declaration with current figures.',
      'Send it with supporting documents before the due date.',
    ],
    notice:
      'If the reassessment is not completed, your benefit may be suspended or reduced.',
  },

  // -------------------------------------------------------------- MORTALITY
  {
    eventCode: 'BENEFITS.MORTALITY.REPORTED',
    templateFamily: 'BENEFITS_MORTALITY_REPORTED',
    recipientRole: 'reporter',
    name: 'Death report received',
    description: 'Acknowledges a reported death to the person who reported it.',
    communicationClass: 'transactional',
    priority: 'high',
    subject: 'We have received your report — reference {{payload.reference}}',
    preheader: 'Thank you for notifying the Board.',
    headline: 'We have received your report',
    intro: [
      'Please accept our condolences. This message confirms that the report you made to the Social Security Board has been received and recorded.',
      'We will now check the report against our records before taking any action on benefits or awards.',
    ],
    details: [
      t('Report reference', 'reference'),
      t('Reported on', 'reportedOn'),
      t('Person reported', 'subjectSummary'),
      t('Current status', 'caseStatus'),
    ],
    nextSteps: [
      'We may contact you for a certified document to verify the report.',
      'Any benefits or awards affected will be reviewed and you will be informed.',
    ],
    closing: 'You do not need to take any further action at this stage.',
  },
  {
    eventCode: 'BENEFITS.MORTALITY.VERIFICATION.REQUESTED',
    templateFamily: 'BENEFITS_MORTALITY_VERIFICATION_REQUESTED',
    recipientRole: 'reporter',
    name: 'Death verification requested',
    description: 'Requests documentary verification of a reported death.',
    communicationClass: 'transactional',
    priority: 'high',
    subject: 'Verification needed for report {{payload.reference}}',
    preheader: 'We need a document to verify the report.',
    headline: 'We need a document to verify the report',
    intro: [
      'Before we can act on the report you made, we must verify it against an official document.',
    ],
    details: [
      t('Report reference', 'reference'),
      t('Document required', 'evidenceRequested'),
      t('Send by', 'dueDate'),
      t('How to send', 'submissionChannel'),
    ],
    nextSteps: [
      'Send a certified copy of the document listed above.',
      'Contact us if the document is not yet available.',
    ],
    closing: 'We are sorry to ask for paperwork at a difficult time.',
  },
  {
    eventCode: 'BENEFITS.MORTALITY.REJECTED',
    templateFamily: 'BENEFITS_MORTALITY_REJECTED',
    recipientRole: 'reporter',
    name: 'Death report not accepted',
    description: 'Explains why a reported death could not be accepted.',
    communicationClass: 'transactional',
    priority: 'high',
    subject: 'We could not accept report {{payload.reference}}',
    preheader: 'The report could not be verified.',
    headline: 'We could not accept the report',
    intro: [
      'We have examined the report you made. It cannot be accepted at this time for the reason set out below.',
    ],
    details: [
      t('Report reference', 'reference'),
      t('Reason', 'rejectionReason'),
      t('What is needed', 'resolutionRequirement'),
      t('Decided on', 'decisionDate'),
    ],
    nextSteps: [
      'Send the item described above if you are able to obtain it.',
      'Contact us if you believe the record we hold is wrong.',
    ],
    notice: 'No benefit or award has been changed as a result of this report.',
  },
  {
    eventCode: 'BENEFITS.MORTALITY.AWARDS.TERMINATED',
    templateFamily: 'BENEFITS_MORTALITY_AWARDS_TERMINATED',
    recipientRole: 'estate_representative',
    name: 'Awards terminated following death',
    description:
      'Informs the estate representative that awards have been terminated following a verified death.',
    communicationClass: 'legal_mandatory',
    priority: 'high',
    subject: 'Benefit awards ended — reference {{payload.reference}}',
    preheader: 'Awards have been terminated following a verified death.',
    headline: 'Benefit awards have been ended',
    intro: [
      'Following verification of the death recorded on our system, the benefit awards listed below have been terminated.',
      'This notice is sent so that the estate has a written record of the position.',
    ],
    details: [
      t('Case reference', 'reference'),
      t('Awards ended', 'awardSummary'),
      t('Effective date', 'terminationDate'),
      t('Any final amount due', 'finalPaymentSummary'),
      t('Any amount overpaid', 'overpaidAmount'),
    ],
    nextSteps: [
      'Return any payment received after the effective date.',
      'Contact us about any final amount due to the estate.',
      'Ask us about survivor or funeral benefits if they may apply.',
    ],
  },
  {
    eventCode: 'BENEFITS.MORTALITY.SURVIVOR_ASSESSMENT.STARTED',
    templateFamily: 'BENEFITS_MORTALITY_SURVIVOR_ASSESSMENT_STARTED',
    recipientRole: 'survivor',
    name: 'Survivor assessment started',
    description: 'Tells a potential survivor that an assessment has begun.',
    communicationClass: 'transactional',
    priority: 'high',
    subject: 'We are assessing your possible survivor entitlement',
    preheader: 'A survivor benefit assessment has started.',
    headline: 'We are assessing your possible survivor entitlement',
    intro: [
      'Following a death recorded with the Board, we have started an assessment of whether you may be entitled to a survivor benefit.',
    ],
    details: [
      t('Case reference', 'reference'),
      t('Assessment started', 'assessmentStartedOn'),
      t('Information we may need', 'informationRequested'),
      t('Expected next contact', 'nextMilestone'),
    ],
    nextSteps: [
      'Gather identification and proof of relationship in advance.',
      'Respond promptly if we write to you asking for documents.',
    ],
    closing: 'Please accept our condolences.',
  },
  {
    eventCode: 'BENEFITS.MORTALITY.FUNERAL_BENEFIT.OPPORTUNITY',
    templateFamily: 'BENEFITS_MORTALITY_FUNERAL_BENEFIT_OPPORTUNITY',
    recipientRole: 'funeral_claimant',
    name: 'Funeral benefit may be claimable',
    description:
      'Tells the person who met funeral costs that a funeral benefit may be claimable.',
    communicationClass: 'service',
    priority: 'normal',
    subject: 'You may be able to claim a funeral benefit',
    preheader: 'A funeral benefit may be available in this case.',
    headline: 'You may be able to claim a funeral benefit',
    intro: [
      'Our records indicate that a funeral benefit may be claimable in connection with the case below.',
      'This is not a decision on entitlement — it is an invitation to make a claim so that entitlement can be assessed.',
    ],
    details: [
      t('Case reference', 'reference'),
      t('Benefit that may apply', 'benefitType'),
      t('Documents usually needed', 'evidenceRequested'),
      t('Claim by', 'dueDate'),
    ],
    nextSteps: [
      'Complete a funeral benefit claim form.',
      'Attach the receipts and documents listed above.',
      'Submit the claim before the time limit shown.',
    ],
    notice:
      'Time limits apply to funeral benefit claims. A late claim may not be payable.',
  },

  // ------------------------------------------------------------------- RISK
  {
    eventCode: 'BENEFITS.RISK.VERIFICATION.REQUESTED',
    templateFamily: 'BENEFITS_RISK_VERIFICATION_REQUESTED',
    recipientRole: 'claimant',
    name: 'Verification of details requested',
    description:
      'Neutral request to verify details as part of routine assurance checks; discloses no risk assessment.',
    communicationClass: 'transactional',
    priority: 'high',
    subject: 'Please confirm some details on your record',
    preheader: 'We need you to confirm details held on your record.',
    headline: 'Please confirm some details on your record',
    intro: [
      'As part of routine checks on benefit records, we need you to confirm the details listed below.',
      'This is a standard verification. It does not by itself mean anything is wrong with your claim or award.',
    ],
    details: [
      t('Case reference', 'reference'),
      t('Details to confirm', 'informationRequested'),
      t('Respond by', 'dueDate'),
      t('How to respond', 'submissionChannel'),
    ],
    nextSteps: [
      'Check each detail listed above.',
      'Tell us whether it is correct, or send the corrected information.',
      'Respond before the date shown.',
    ],
    notice:
      'If we do not hear from you by {{payload.dueDate}}, your payments may be held while the check is completed.',
  },
];
